"use client";

import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { CaseShell } from "@/components/cases/CaseEngine";

type Step="story"|"clues"|"facts"|"challenge"|"problem"|"solved"|"file"|"reward";
type Q={prompt:string;choices:string[];correct:number;feedback:string};
const btn="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-detective-orange-500 px-6 py-3 font-display font-bold text-white";
const scenes=[
{title:"Mia’s Big Idea",text:"Mia imagines a brand-new Star Dragon and begins drawing it in her own special way."},
{title:"From Idea to Creation",text:"Mia turns her idea into something we can see: a rough sketch, a coloured drawing and a short Star Dragon comic."},
{title:"The Copycat Surprise",text:"Mia spots a very similar Star Dragon displayed under someone else’s name. Questy knows it is time to investigate."},
{title:"Your Mission",text:"What belongs to Mia? What evidence can help show that she created it? Follow the trail like a real IP detective."}
];
const storyQs:Q[]=[
{prompt:"What did Mia create from her own imagination?",choices:["A Star Dragon character","Questy’s hat","A shop building","A football"],correct:0,feedback:"Correct! Mia expressed her own Star Dragon character."},
{prompt:"Which item can help show how Mia developed her creation?",choices:["Her rough sketch","Someone else’s backpack","A random receipt","A playground map"],correct:0,feedback:"Exactly. Early sketches can be useful evidence of the creative process."},
{prompt:"What happened after Mia finished her Star Dragon?",choices:["A similar drawing appeared under another child’s name","The drawing disappeared forever","Questy invented a robot","Mia stopped drawing"],correct:0,feedback:"Correct. That is the mystery Questy and Mia need to investigate."},
{prompt:"What should a good detective do first?",choices:["Check the evidence","Guess immediately","Ignore the drafts","Choose the loudest person"],correct:0,feedback:"Correct! Evidence is more useful than guessing."},
{prompt:"Which evidence is strongest for showing Mia’s creative process?",choices:["Her dated sketches and drafts","A friend saying she likes dragons","The colour of her pencil case","A poster from another event"],correct:0,feedback:"Great detective work. Drafts and dated working materials can help show how a work developed."}
];
const challenges:Q[]=[
{prompt:"Mia thinks of a dragon but never draws or writes it down. Is the idea alone the same as a finished creative work?",choices:["No — expression matters","Yes — every thought is automatically a finished work","Only if Questy hears it","Only at Creator Park"],correct:0,feedback:"Correct. Copyright protects original expression rather than an abstract idea by itself."},
{prompt:"Mia draws an original Star Dragon. What kind of IP is most directly relevant to the drawing?",choices:["Copyright","Patent","A domain name","A trade licence"],correct:0,feedback:"Correct. Original drawings are the kind of creative works copyright can protect."},
{prompt:"Why should Mia keep her sketches and drafts?",choices:["They can help document her creative process","They automatically create a patent","They make every idea secret","They replace the finished work"],correct:0,feedback:"Correct. Keeping drafts can provide useful evidence about creation and development."},
{prompt:"Another child independently draws a completely different dragon. Does Mia own every dragon drawing?",choices:["No — Mia’s rights concern her own original expression","Yes — Mia owns all dragons","Yes — if both use pencils","No — because drawings never matter"],correct:0,feedback:"Correct. Copyright does not give someone ownership of a general idea such as drawing a dragon."},
{prompt:"What is the best detective rule from this case?",choices:["Recognise creators and check evidence","The first person to display something always created it","Ideas and finished works are identical","Never keep drafts"],correct:0,feedback:"Excellent. Recognise the creator and use evidence to understand how the work was made."}
];
function Art({n,title}:{n:number;title:string}){return <picture><source media="(orientation: portrait)" srcSet={`/cases/world-3/Scene ${n} - Portrait.png`}/><Image src={`/cases/world-3/Scene ${n} - Landscape.png`} alt={title} width={1672} height={941} sizes="(max-width:1024px) 100vw,896px" className="mt-4 h-auto w-full rounded-2xl object-contain"/></picture>}
function Question({title,q,index,total,onNext}:{title:string;q:Q;index:number;total:number;onNext:()=>void}){const[ok,setOk]=useState(false);const[msg,setMsg]=useState("");useEffect(()=>{if(!ok)return;const t=setTimeout(onNext,900);return()=>clearTimeout(t)},[ok,onNext]);return <section className="rounded-3xl bg-white p-5 text-center shadow-sm sm:p-7"><p className="font-display font-bold uppercase tracking-widest text-detective-orange-600">{title} · {index+1} of {total}</p><h2 className="mx-auto mt-3 max-w-2xl font-display text-2xl font-bold text-detective-blue-900">{q.prompt}</h2><div className="mx-auto mt-6 grid max-w-2xl gap-3">{q.choices.map((c,i)=><button key={c} disabled={ok} onClick={()=>{const right=i===q.correct;setOk(right);setMsg(right?q.feedback:"Good try, Detective. Check the evidence and try again!")}} className={`min-h-14 rounded-2xl border-2 px-5 py-3 text-left text-lg font-semibold ${ok&&i===q.correct?"border-green-500 bg-green-50":"border-detective-blue-100 bg-sky-50 hover:border-detective-orange-400"}`}>{String.fromCharCode(65+i)}. {c}</button>)}</div>{msg&&<p className="mx-auto mt-5 max-w-2xl rounded-2xl bg-detective-yellow-100 p-4 font-display font-bold">{msg}</p>}</section>}
export function CaseThreeExperience({isCompleted,onComplete}:{isCompleted:boolean;onComplete:(correct:number,total:number)=>void}){const[step,setStep]=useState<Step>("story");const[scene,setScene]=useState(0);const[q,setQ]=useState(0);const[ch,setCh]=useState(0);const done=useRef(false);const finish=()=>{if(!isCompleted&&!done.current){done.current=true;onComplete(10,10)}setStep("solved")};const shell=step==="story"?"story":step==="clues"?"investigate":step==="facts"?"discovery":step==="challenge"?"clues":step==="problem"?"problem":step==="solved"?"solved":step;return <CaseShell step={shell}>
{step==="story"&&<section className="rounded-3xl bg-white p-4 shadow-sm sm:p-6"><p className="font-display text-sm font-bold uppercase tracking-widest text-detective-orange-600">World 3 · Creator Park · Scene {scene+1} of 4</p><h2 className="mt-2 font-display text-3xl font-bold text-detective-blue-900">My Creation Matters</h2><h3 className="mt-2 font-display text-2xl font-bold">{scenes[scene].title}</h3><Art n={scene+1} title={scenes[scene].title}/><p className="mt-5 rounded-2xl bg-sky-50 p-4 text-lg">{scenes[scene].text}</p><nav className="mt-5 flex justify-between gap-3"><button disabled={!scene} onClick={()=>setScene(scene-1)} className="min-h-12 rounded-full border-2 px-5 font-display font-bold disabled:invisible"><ArrowLeft className="mr-2 inline h-4 w-4"/>BACK</button><button onClick={()=>scene===3?setStep("clues"):setScene(scene+1)} className={btn}>{scene===3?"START INVESTIGATION":"NEXT"}<ArrowRight className="h-4 w-4"/></button></nav></section>}
{step==="clues"&&<Question key={`q${q}`} title="🔎 STORY INVESTIGATION" q={storyQs[q]} index={q} total={5} onNext={()=>q<4?setQ(q+1):setStep("facts")}/>} 
{step==="facts"&&<section className="rounded-3xl bg-white p-5 shadow-sm sm:p-7"><h2 className="font-display text-3xl font-bold text-detective-blue-900">📖 CREATOR FACTS</h2><div className="mt-5 space-y-4 text-lg"><p className="rounded-2xl bg-sky-50 p-5"><strong>Ideas and expression:</strong> An idea in your head is different from the way you express it in a drawing, story, photograph, song or other creative work.</p><p className="rounded-2xl bg-sky-50 p-5"><strong>Copyright:</strong> Original creative expression can be protected by copyright. Copyright generally protects the expression, not the general idea itself.</p><p className="rounded-2xl bg-sky-50 p-5"><strong>Evidence:</strong> Sketches, drafts, working files and dates can help document how a creation developed and who worked on it.</p><p className="rounded-2xl bg-detective-yellow-100 p-5 font-display font-bold">Questy’s Rule: Create it. Keep your drafts. Respect other creators.</p></div><button className={`${btn} mt-6`} onClick={()=>setStep("challenge")}>DETECTIVE CHALLENGE <ArrowRight className="h-4 w-4"/></button></section>}
{step==="challenge"&&<Question key={`ch${ch}`} title="🏅 DETECTIVE CHALLENGE" q={challenges[ch]} index={ch} total={5} onNext={()=>ch<4?setCh(ch+1):setStep("problem")}/>} 
{step==="problem"&&<section className="rounded-3xl bg-white p-5 shadow-sm sm:p-7"><h2 className="font-display text-3xl font-bold text-detective-blue-900">🚨 FINAL PROBLEM · WHO CREATED STAR DRAGON?</h2><p className="mt-4 text-lg">Mia has an early dated sketch, a later coloured draft and her finished Star Dragon comic. Another child only has a similar finished picture displayed later. Which evidence best helps investigate who developed Mia’s Star Dragon artwork?</p><Question title="SOLVE THE CASE" index={0} total={1} q={{prompt:"Choose the strongest evidence trail.",choices:["Mia’s dated sketch → coloured draft → finished comic","Whoever displayed a picture most recently","Whoever speaks first","The colour of the display board"],correct:0,feedback:"Case solved! Mia’s sequence of working materials documents the development of her creative work."}} onNext={finish}/></section>}
{step==="solved"&&<section className="rounded-3xl bg-gradient-to-br from-detective-yellow-100 to-sky-100 p-6 text-center"><h2 className="font-display text-4xl font-bold text-detective-blue-900">🎉 WORLD 3 SOLVED!</h2><p className="mt-3 text-2xl">My Creation Matters</p><p className="mt-4 text-lg">You learned that original creative expression matters — and that drafts can help tell the story of how something was created.</p><p className="mt-5 rounded-2xl bg-white p-5 font-display text-2xl font-bold">🏅 CREATOR DETECTIVE BADGE · +70 XP</p><div className="mt-6 flex flex-wrap justify-center gap-3"><button className={btn} onClick={()=>setStep("file")}>VIEW CASE FILE</button><button className={btn} onClick={()=>setStep("reward")}>REWARD ACTIVITY</button></div></section>}
{step==="file"&&<section className="rounded-3xl bg-white p-6"><p className="font-display font-bold uppercase tracking-widest text-detective-orange-600">LITTLE IP DETECTIVES · CASE FILE #3</p><h2 className="mt-2 font-display text-3xl font-bold">My Creation Matters</h2><dl className="mt-5 grid gap-3 sm:grid-cols-2">{[["Mystery","Who created Star Dragon?"],["Creator Word","Expression"],["Discovery","Original creative expression can be protected by copyright."],["Evidence","Sketches and drafts can document the creative process."],["Detective Rule","Create it. Keep your drafts. Respect other creators."],["Status","✅ CASE SOLVED"]].map(([a,b])=><div key={a} className="rounded-2xl bg-sky-50 p-4"><dt className="font-display font-bold">{a}</dt><dd>{b}</dd></div>)}</dl><button className={`${btn} mt-6`} onClick={()=>setStep("reward")}>REWARD ACTIVITY</button></section>}
{step==="reward"&&<section className="rounded-3xl bg-white p-6 text-center"><h2 className="font-display text-3xl font-bold text-detective-blue-900">🎨 CREATE YOUR OWN CHARACTER</h2><p className="mx-auto mt-4 max-w-2xl text-lg">Now it is your turn. Draw an original character and give it a name. Keep your first sketch as part of your creator evidence!</p><div className="mx-auto mt-6 max-w-2xl rounded-3xl border-4 border-dashed border-detective-blue-200 bg-sky-50 p-12"><p className="font-display text-2xl font-bold">Your creation starts here ✏️</p></div><button className={`${btn} mt-6`} onClick={()=>setStep("file")}>VIEW CASE FILE</button></section>}
</CaseShell>}
