"use client";

import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { CaseShell } from "@/components/cases/CaseEngine";
import { CreatorParkPuzzle } from "@/components/cases/CreatorParkPuzzle";

type Step = "story" | "clues" | "discovery" | "challenge" | "problem" | "solved" | "file" | "reward";
type Q = { prompt: string; choices: string[]; correct: number; feedback: string };
const buttonClass = "inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-detective-orange-500 px-6 py-3 font-display font-bold text-white";
const scenes = [
{title:"The Mystery Box",landscape:"/cases/world-2/Scene 1 - Landscape.png",portrait:"/cases/world-2/Scene 1 - Portrait.png",text:"Questy and Mia discover a mysterious box in Creator Park. What could be inside?"},
{title:"Four Strange Clues",landscape:"/cases/world-2/Scene 2 - Landscape.png",portrait:"/cases/world-2/Scene 2 - Portrait.png",text:"Inside are four clues: a logo, an invention, a story and a product design."},
{title:"What Protects What?",landscape:"/cases/world-2/Scene 3 - Landscape.png",portrait:"/cases/world-2/Scene 3 - Portrait.png",text:"Questy and Mia realise that different creations can be protected in different ways."},
{title:"Your Mission",landscape:"/cases/world-2/Scene 4 - Landscape.png",portrait:"/cases/world-2/Scene 4 - Portrait.png",text:"Your mission is to discover four important kinds of IP: trademarks, patents, copyright and designs."}];
const clues:Q[]=[
{prompt:"Which clue helps people recognise a brand?",choices:["A logo","A robot invention","A story","A bottle shape"],correct:0,feedback:"Correct! A logo can function as a trademark and help people recognise a brand."},
{prompt:"Which clue is most closely connected with an invention?",choices:["A shop name","A new robot mechanism","A storybook","A logo"],correct:1,feedback:"Correct! Patents can protect qualifying inventions."},
{prompt:"Which clue is a creative work?",choices:["The Moon Cat story","A brand logo only","A machine mechanism","A shop sign only"],correct:0,feedback:"Correct! Stories and artwork are examples of works that copyright can protect."},
{prompt:"Which clue focuses on how a product looks?",choices:["A secret recipe","A bottle's visual shape and appearance","A story title","A machine's hidden process"],correct:1,feedback:"Correct! Registered designs can protect the visual appearance of eligible products."},
{prompt:"Why did the mystery box contain four different clues?",choices:["All IP is exactly the same","Different creations can involve different types of IP","Only inventions are IP","Only adults create IP"],correct:1,feedback:"Excellent. Different kinds of creations may involve different IP rights."}];
const challenges:Q[]=[
{prompt:"Mia creates a name and logo for a pretend snack shop. Which IP should she investigate first?",choices:["Trademark","Patent","Copyright in a novel","Plant variety protection"],correct:0,feedback:"Trademark is the best match for a brand name or logo."},
{prompt:"Ben invents a genuinely new technical mechanism for his robot. Which IP is most relevant?",choices:["Trademark","Patent","Copyright only","Domain name"],correct:1,feedback:"A patent may protect a qualifying new invention."},
{prompt:"Zara writes and illustrates The Moon Cat. Which IP is most directly connected to the story and artwork?",choices:["Copyright","Patent","Trademark only","Trade secret only"],correct:0,feedback:"Copyright protects original creative works such as stories and illustrations."},
{prompt:"A creator makes a distinctive new visual shape for a reusable bottle. Which IP is most relevant to its appearance?",choices:["Design protection","Patent automatically","Copyright in every case","Trademark automatically"],correct:0,feedback:"Design protection focuses on a product's visual appearance."},
{prompt:"Can one product involve more than one kind of IP?",choices:["No, never","Yes, different features can involve different IP rights","Only if it is expensive","Only in Creator Park"],correct:1,feedback:"Correct! A product can have a brand, creative artwork, an invention and a protected design."}];
function ResponsiveArtwork({landscape,portrait,alt}:{landscape:string;portrait:string;alt:string}){return <picture><source media="(orientation: portrait)" srcSet={portrait}/><Image src={landscape} alt={alt} width={1672} height={941} sizes="(max-width: 1024px) 100vw, 896px" className="mt-4 h-auto w-full rounded-2xl object-contain"/></picture>}
function Question({title,q,index,total,onNext}:{title:string;q:Q;index:number;total:number;onNext:()=>void}){const[correct,setCorrect]=useState(false);const[feedback,setFeedback]=useState("");useEffect(()=>{if(!correct)return;const t=window.setTimeout(onNext,900);return()=>clearTimeout(t)},[correct,onNext]);return <section className="rounded-3xl bg-white p-5 text-center shadow-sm sm:p-7"><p className="font-display font-bold uppercase tracking-widest text-detective-orange-600">{title} · {index+1} of {total}</p><h2 className="mx-auto mt-3 max-w-2xl font-display text-2xl font-bold text-detective-blue-900">{q.prompt}</h2><div className="mx-auto mt-6 grid max-w-2xl gap-3">{q.choices.map((c,i)=><button key={c} disabled={correct} onClick={()=>{const ok=i===q.correct;setCorrect(ok);setFeedback(ok?q.feedback:"Good try, Detective. Look at the clues and try again!")}} className={`min-h-14 rounded-2xl border-2 px-5 py-3 text-left text-lg font-semibold ${correct&&i===q.correct?"border-green-500 bg-green-50":"border-detective-blue-100 bg-sky-50 hover:border-detective-orange-400"}`}>{String.fromCharCode(65+i)}. {c}</button>)}</div>{feedback&&<p className="mx-auto mt-5 max-w-2xl rounded-2xl bg-detective-yellow-100 p-4 font-display font-bold">{feedback}</p>}</section>}
export function CaseTwoExperience({isCompleted,onComplete}:{isCompleted:boolean;onComplete:(correct:number,total:number)=>void}){const[step,setStep]=useState<Step>("story");const[scene,setScene]=useState(0);const[clue,setClue]=useState(0);const[challenge,setChallenge]=useState(0);const completed=useRef(false);const finish=()=>{if(!isCompleted&&!completed.current){completed.current=true;onComplete(10,10)}setStep("solved")};const shellStep=step==="story"?"story":step==="clues"?"investigate":step==="discovery"?"discovery":step==="challenge"?"clues":step==="problem"?"problem":step==="solved"?"solved":step;return <CaseShell step={shellStep}>
{step==="story"&&<section className="rounded-3xl bg-white p-4 shadow-sm sm:p-6"><p className="font-display text-sm font-bold uppercase tracking-widest text-detective-orange-600">World 2 · Creator Park · Scene {scene+1} of 4</p><h2 className="mt-2 font-display text-3xl font-bold text-detective-blue-900">The World of Ideas</h2><h3 className="mt-2 font-display text-2xl font-bold text-detective-blue-800">{scenes[scene].title}</h3><ResponsiveArtwork landscape={scenes[scene].landscape} portrait={scenes[scene].portrait} alt={scenes[scene].title}/><p className="mt-5 rounded-2xl bg-sky-50 px-4 py-3 text-lg text-detective-blue-900">{scenes[scene].text}</p><nav className="mt-5 flex items-center justify-between gap-3"><button disabled={scene===0} onClick={()=>setScene(scene-1)} className="min-h-12 rounded-full border-2 border-detective-blue-200 px-5 font-display font-bold disabled:invisible"><ArrowLeft className="mr-2 inline h-4 w-4"/>BACK</button><button onClick={()=>scene===3?setStep("clues"):setScene(scene+1)} className={buttonClass}>{scene===3?"START INVESTIGATION":"NEXT"}<ArrowRight className="h-4 w-4"/></button></nav></section>}
{step==="clues"&&<Question key={`c${clue}`} title="🔎 FIND THE CLUES" q={clues[clue]} index={clue} total={5} onNext={()=>clue<4?setClue(clue+1):setStep("discovery")}/>} 
{step==="discovery"&&<section className="rounded-3xl bg-white p-5 shadow-sm sm:p-7"><h2 className="font-display text-3xl font-bold text-detective-blue-900">🔎 QUESTY’S DISCOVERY</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Fact title="™ TRADEMARKS">Help distinguish the goods or services of one business from others. Names and logos are common examples.</Fact><Fact title="💡 PATENTS">Can protect qualifying inventions that meet legal requirements such as novelty and inventiveness.</Fact><Fact title="📚 COPYRIGHT">Protects original creative expression such as stories, drawings, music and other works.</Fact><Fact title="✏️ DESIGNS">Can protect the visual features of eligible products, such as shape, configuration, pattern or ornament.</Fact></div><div className="mt-5 rounded-2xl bg-detective-yellow-100 p-5 text-lg"><strong>Questy’s rule:</strong> Look at what was created. Is it a brand, invention, creative work or product appearance? That gives you a clue about the type of IP to investigate.</div><button className={`${buttonClass} mt-6`} onClick={()=>setStep("challenge")}>TAKE THE DETECTIVE CHALLENGE <ArrowRight className="h-4 w-4"/></button></section>}
{step==="challenge"&&<Question key={`d${challenge}`} title="🏅 DETECTIVE CHALLENGE" q={challenges[challenge]} index={challenge} total={5} onNext={()=>challenge<4?setChallenge(challenge+1):setStep("problem")}/>} 
{step==="problem"&&<section className="rounded-3xl bg-white p-5 shadow-sm sm:p-7"><h2 className="font-display text-3xl font-bold text-detective-blue-900">🚨 FINAL PROBLEM · THE MIXED-UP EXHIBITION</h2><ResponsiveArtwork landscape="/cases/world-2/Final Problem - Landscape.png" portrait="/cases/world-2/Final Problem - Portrait.png" alt="The Mixed-Up Exhibition final problem"/><p className="mt-5 text-lg text-detective-blue-900">The Creator Park exhibition labels have been mixed up. Which matching set puts all four creations with the most relevant type of IP?</p><Question title="SOLVE THE CASE" index={0} total={1} q={{prompt:"Choose the correct set.",choices:["Logo—Trademark · Robot invention—Patent · Moon Cat story—Copyright · Bottle appearance—Design","Logo—Patent · Robot—Copyright · Story—Design · Bottle—Trademark","Everything—Patent","Everything—Trademark"],correct:0,feedback:"Case solved! Different creations can involve different kinds of intellectual property."}} onNext={finish}/></section>}
{step==="solved"&&<section className="rounded-3xl bg-gradient-to-br from-detective-yellow-100 to-sky-100 p-6 text-center"><h2 className="font-display text-4xl font-bold text-detective-blue-900">🎉 WORLD 2 SOLVED!</h2><p className="mt-3 text-2xl">The World of Ideas</p><p className="mt-4">You discovered how trademarks, patents, copyright and designs connect to different creations.</p><p className="mt-5 rounded-2xl bg-white p-5 font-display text-2xl font-bold">🏅 IP EXPLORER BADGE · +60 XP</p><div className="mt-6 flex flex-wrap justify-center gap-3"><button className={buttonClass} onClick={()=>setStep("file")}>VIEW CASE FILE</button><button className={buttonClass} onClick={()=>setStep("reward")}>CREATOR PARK PUZZLE</button></div></section>}
{step==="file"&&<section className="rounded-3xl bg-white p-6"><p className="font-display font-bold uppercase tracking-widest text-detective-orange-600">LITTLE IP DETECTIVES · CASE FILE #2</p><h2 className="mt-2 font-display text-3xl font-bold">The World of Ideas</h2><dl className="mt-5 grid gap-3 sm:grid-cols-2">{[["Mystery","What protects what?"],["Trademark","Brands and signs that distinguish goods or services"],["Patent","Qualifying inventions"],["Copyright","Original creative works"],["Design","Visual appearance of eligible products"],["Status","✅ CASE SOLVED"]].map(([a,b])=><div key={a} className="rounded-2xl bg-sky-50 p-4"><dt className="font-display font-bold">{a}</dt><dd>{b}</dd></div>)}</dl><button className={`${buttonClass} mt-6`} onClick={()=>setStep("reward")}>CREATOR PARK PUZZLE</button></section>}
{step==="reward"&&<CreatorParkPuzzle onFile={()=>setStep("file")}/>} 
</CaseShell>}
function Fact({title,children}:{title:string;children:React.ReactNode}){return <article className="rounded-3xl border-2 border-detective-yellow-200 bg-detective-yellow-50 p-5 text-lg"><h3 className="mb-2 font-display text-xl font-bold">{title}</h3>{children}</article>}
