"use client";
import Image from "next/image";
import { useEffect,useRef,useState } from "react";
import { ArrowLeft,ArrowRight } from "lucide-react";
import { CaseShell } from "@/components/cases/CaseEngine";
import { BrandStreetMakeover } from "@/components/cases/BrandStreetMakeover";
import { ReadToMeButton } from "@/components/audio/ReadToMeButton";
import { playCelebrationSound } from "@/lib/audio";
type Step="story"|"clues"|"facts"|"challenge"|"problem"|"solved"|"file"|"reward"; type Q={prompt:string;choices:string[];correct:number;feedback:string};
const btn="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-detective-orange-500 px-6 py-3 font-display font-bold text-white";
const scenes=[{title:"Welcome to Brand Street",text:"Questy and the adventurers arrive on Brand Street, where special names help customers tell one business from another."},{title:"Mia’s New Shop",text:"Mia’s cupcakes look delicious, but her sign only says CUPCAKES. Customers keep asking what her shop is called."},{title:"The Confusing Shops",text:"CUPCAKES, SWEET CUPCAKES and BEST CUPCAKES sound very similar. A more distinctive name can make a particular business easier to recognise and remember."},{title:"Your Mission",text:"What makes a good brand name? Help Mia choose a name that customers can recognise and remember."}];
const storyQs:Q[]=[{prompt:"Why can a brand name be useful to a business?",choices:["It changes the recipe","It helps customers identify and remember the business","It makes every product free","It tells customers the weather"],correct:1,feedback:"Yes! A brand name can help customers recognise and remember a particular business."},{prompt:"Mia’s sign only says CUPCAKES. What does that word mainly tell customers?",choices:["Who invented cupcakes","Where Mia lives","What kind of product she sells","How many cupcakes she baked"],correct:2,feedback:"Exactly. CUPCAKES mainly describes the product being sold."},{prompt:"Four juice shops are opening. Which name stands out most?",choices:["FRESH JUICE","BEST JUICE","JUICE SHOP","ZIPPORA"],correct:3,feedback:"Great spotting! ZIPPORA is an invented name and stands apart from the descriptive juice-shop names in this fictional example."},{prompt:"What should Questy look for when several shop names seem alike?",choices:["A name that helps distinguish one business from another","The biggest cupcake","The tallest customer","The shop with the most chairs"],correct:0,feedback:"Correct. A useful brand clue helps people distinguish one business from another."},{prompt:"What problem can similar shop names create?",choices:["Cupcakes become smaller","Every shop must close","Customers may become confused about which business is which","The street changes colour"],correct:2,feedback:"Correct! Similar names can make it harder for customers to know which business they are dealing with."}];
const challenges:Q[]=[{prompt:"Arjun opens a banana smoothie shop. Which fictional name gives it a more distinctive identity?",choices:["BANANA SMOOTHIES","FRESH BANANA DRINKS","BANANA SHOP","BANAZOO"],correct:3,feedback:"BANAZOO stands apart more clearly from the descriptive choices."},{prompt:"Which statement best describes a brand name?",choices:["A name used to help identify a particular business, product or service","A list of ingredients","A shop’s opening hours","A receipt number"],correct:0,feedback:"Correct. A brand name is an identity clue."},{prompt:"Two cafés have very similar names and customers keep entering the wrong one. What happened?",choices:["They invented a recipe","The street moved","The names are causing confusion","The cafés became schools"],correct:2,feedback:"Exactly. The similar names are making it harder to tell the businesses apart."},{prompt:"Which choice mainly describes the goods?",choices:["ZINGORA","ICE CREAM SHOP","MOONMINT","FROSTIPOP"],correct:1,feedback:"Correct. ICE CREAM SHOP directly describes the kind of shop."},{prompt:"What is Questy’s best rule for this adventure?",choices:["Copy a famous name","Always use the longest name","Only use the product name","Don’t just describe it — give your brand its own identity"],correct:3,feedback:"Excellent! Give your brand its own identity."}];
function Art({n,title}:{n:number;title:string}){return <picture><source media="(orientation: portrait)" srcSet={`/cases/world-4/Scene ${n} Portrait.png`}/><Image src={`/cases/world-4/Scene ${n} Landscape.png`} alt={title} width={1672} height={941} sizes="(max-width:1024px) 100vw,896px" className="mt-4 h-auto w-full rounded-2xl object-contain"/></picture>}
function Question({title,q,index,total,onNext}:{title:string;q:Q;index:number;total:number;onNext:()=>void}){const[ok,setOk]=useState(false);const[msg,setMsg]=useState("");useEffect(()=>{if(!ok)return;const t=setTimeout(onNext,900);return()=>clearTimeout(t)},[ok,onNext]);return <section className="rounded-3xl bg-white p-5 text-center shadow-sm sm:p-7"><p className="font-display font-bold uppercase tracking-widest text-detective-orange-600">{title} · {index+1} of {total}</p><h2 className="mx-auto mt-3 max-w-2xl font-display text-2xl font-bold text-detective-blue-900">{q.prompt}</h2><ReadToMeButton text={`${q.prompt}. ${q.choices.map((c,i)=>`Option ${String.fromCharCode(65+i)}: ${c}`).join(". ")}`} label="Listen" className="mx-auto mt-4 justify-center"/><div className="mx-auto mt-6 grid max-w-2xl gap-3">{q.choices.map((c,i)=><button key={c} disabled={ok} onClick={()=>{const right=i===q.correct;setOk(right);setMsg(right?q.feedback:"Good try! Look at the clues and try again.")}} className={`min-h-14 rounded-2xl border-2 px-5 py-3 text-left text-lg font-semibold ${ok&&i===q.correct?"border-green-500 bg-green-50":"border-detective-blue-100 bg-sky-50 hover:border-detective-orange-400"}`}>{String.fromCharCode(65+i)}. {c}</button>)}</div>{msg&&<p className="mx-auto mt-5 max-w-2xl rounded-2xl bg-detective-yellow-100 p-4 font-display font-bold">{msg}</p>}</section>}
export function CaseFourExperience({isCompleted,onComplete}:{isCompleted:boolean;onComplete:(correct:number,total:number)=>void}){const[step,setStep]=useState<Step>("story");const[scene,setScene]=useState(0);const[q,setQ]=useState(0);const[ch,setCh]=useState(0);const done=useRef(false);const finish=()=>{playCelebrationSound();if(!isCompleted&&!done.current){done.current=true;onComplete(10,10)}setStep("solved")};const shell=step==="story"?"story":step==="clues"?"investigate":step==="facts"?"discovery":step==="challenge"?"clues":step==="problem"?"problem":step==="solved"?"solved":step;return <CaseShell step={shell}>
{step==="story"&&<section className="rounded-3xl bg-white p-4 shadow-sm sm:p-6"><p className="font-display text-sm font-bold uppercase tracking-widest text-detective-orange-600">Adventure 4 · Brand Street · Part {scene+1} of 4</p><h2 className="mt-2 font-display text-3xl font-bold text-detective-blue-900">The Mystery of the Brand Name</h2><h3 className="mt-2 font-display text-2xl font-bold">{scenes[scene].title}</h3><ReadToMeButton text={`${scenes[scene].title}. ${scenes[scene].text}`} className="mt-4"/><Art n={scene+1} title={scenes[scene].title}/><p className="mt-5 rounded-2xl bg-sky-50 p-4 text-lg">{scenes[scene].text}</p><nav className="mt-5 flex justify-between gap-3"><button disabled={!scene} onClick={()=>setScene(scene-1)} className="min-h-12 rounded-full border-2 px-5 font-display font-bold disabled:invisible"><ArrowLeft className="mr-2 inline h-4 w-4"/>BACK</button><button onClick={()=>scene===3?setStep("clues"):setScene(scene+1)} className={btn}>{scene===3?"TRY THE QUESTIONS":"NEXT"}<ArrowRight className="h-4 w-4"/></button></nav></section>}
{step==="clues"&&<Question key={`q${q}`} title="🔎 FUN QUESTIONS" q={storyQs[q]} index={q} total={5} onNext={()=>q<4?setQ(q+1):setStep("facts")}/>} 
{step==="facts"&&<section className="rounded-3xl bg-white p-5 shadow-sm sm:p-7"><h2 className="font-display text-3xl font-bold text-detective-blue-900">💡 QUESTY’S DISCOVERY</h2><ReadToMeButton text="A brand name can help customers identify a particular business, product or service. Names that stand apart can be easier to recognise and remember. Words that simply name or describe the goods may do less to identify one particular business. Questy's rule: Don't just describe it. Give your brand its own identity!" className="mt-4"/><div className="mt-5 grid gap-4 sm:grid-cols-2"><p className="rounded-2xl bg-sky-50 p-5"><strong>🏷️ Brand name:</strong> A name used to help customers identify a particular business, product or service.</p><p className="rounded-2xl bg-sky-50 p-5"><strong>👀 Identification:</strong> Brand clues can help people tell one business’s goods or services from another’s.</p><p className="rounded-2xl bg-sky-50 p-5"><strong>🧠 Names that stand apart:</strong> They can be easier for customers to recognise and remember.</p><p className="rounded-2xl bg-sky-50 p-5"><strong>⚠️ Descriptive words:</strong> Words that simply name or describe the goods may do less to identify one particular business.</p></div><p className="mt-4 rounded-2xl bg-detective-yellow-100 p-5 font-display text-lg font-bold">🐱 Questy’s Rule: Don’t just describe it. Give your brand its own identity!</p><button className={`${btn} mt-6`} onClick={()=>setStep("challenge")}>KEEP EXPLORING <ArrowRight className="h-4 w-4"/></button></section>}
{step==="challenge"&&<Question key={`ch${ch}`} title="⭐ QUESTY’S CHALLENGE" q={challenges[ch]} index={ch} total={5} onNext={()=>ch<4?setCh(ch+1):setStep("problem")}/>} 
{step==="problem"&&<section className="rounded-3xl bg-white p-5 shadow-sm sm:p-7"><h2 className="font-display text-3xl font-bold text-detective-blue-900">🚨 FINAL CHALLENGE · HELP MIA CHOOSE</h2><p className="mt-4 text-lg">Mia wants a name that stands apart from simple descriptions such as CUPCAKE SHOP. Which fictional option gives her shop the clearest identity in this example?</p><Question title="CHOOSE" index={0} total={1} q={{prompt:"Choose Mia’s strongest brand-name clue.",choices:["DELICIOUS CUPCAKES","SPARKLE BITES","CUPCAKE SHOP","SWEET CUPCAKES"],correct:1,feedback:"You got it! SPARKLE BITES stands apart more clearly from the descriptive cupcake names in this fictional example."}} onNext={finish}/></section>}
{step==="solved"&&<section className="rounded-3xl bg-gradient-to-br from-detective-yellow-100 to-sky-100 p-6 text-center"><h2 className="font-display text-4xl font-bold text-detective-blue-900">🎉 ADVENTURE 4 COMPLETE!</h2><p className="mt-3 text-2xl">The Mystery of the Brand Name</p><p className="mt-4 text-lg">You discovered how brand names can help customers recognise businesses.</p><p className="mt-5 rounded-2xl bg-white p-5 font-display text-2xl font-bold">🏅 BRAND EXPLORER BADGE · +80 XP</p><div className="mt-6 flex flex-wrap justify-center gap-3"><button className={btn} onClick={()=>setStep("file")}>VIEW ADVENTURE CARD</button><button className={btn} onClick={()=>setStep("reward")}>BRAND STREET MAKEOVER 🏪</button></div></section>}
{step==="file"&&<section className="rounded-3xl bg-white p-6"><p className="font-display font-bold uppercase tracking-widest text-detective-orange-600">QUESTY’S IDEA ADVENTURES · ADVENTURE CARD #4</p><h2 className="mt-2 font-display text-3xl font-bold">The Mystery of the Brand Name</h2><dl className="mt-5 grid gap-3 sm:grid-cols-2">{[["Big question","How can Mia make her cupcake shop easier to identify?"],["New word","Brand"],["Discovery","A brand name can help customers identify a particular business, product or service."],["Questy’s tip","Don’t just describe it. Give your brand its own identity!"],["Status","🌟 ADVENTURE COMPLETE"]].map(([a,b])=><div key={a} className="rounded-2xl bg-sky-50 p-4"><dt className="font-display font-bold">{a}</dt><dd>{b}</dd></div>)}</dl><button className={`${btn} mt-6`} onClick={()=>setStep("reward")}>BRAND STREET MAKEOVER 🏪</button></section>}
{step==="reward"&&<section className="rounded-3xl bg-white p-4 text-center sm:p-6"><p className="font-display font-bold uppercase tracking-widest text-detective-orange-600">ADVENTURE 4 REWARD</p><h2 className="mt-2 font-display text-3xl font-bold text-detective-blue-900">🏪 BRAND STREET MAKEOVER</h2><p className="mx-auto mt-3 max-w-2xl text-lg">Create a fictional shop identity and open your very own shop on Brand Street.</p><BrandStreetMakeover/><button className="mt-6 min-h-12 rounded-full border-2 border-detective-blue-200 px-6 font-display font-bold" onClick={()=>setStep("file")}>VIEW ADVENTURE CARD</button></section>}
</CaseShell>}
