import type { Metadata } from "next";
import Image from "next/image";
import { CallToAction } from "@/components/sections/CallToAction";
import { SiteFooter } from "@/components/layout/SiteFooter";
import { SiteHeader } from "@/components/layout/SiteHeader";
import { Container } from "@/components/ui/Container";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { questyArt } from "@/lib/questy-art";
import { creatorQuestions, everydayIp, fourBigIdeas, learningPromise, whyIpMatters } from "@/lib/about-content";

export const metadata: Metadata = { title:"About IP2Kids | Free Intellectual Property Learning for Kids", description:"IP2Kids is a free personal educational initiative helping children explore creativity, brands, inventions, copyright and design through age-appropriate adventures." };

export default function AboutPage(){return <><a href="#main" className="sr-only focus:not-sr-only">Skip to main content</a><SiteHeader/><main id="main">
<section className="relative overflow-hidden bg-gradient-to-b from-detective-blue-50 via-white to-white"><Container className="relative grid items-center gap-10 py-16 lg:grid-cols-2 lg:py-24"><div className="text-center lg:text-left"><p className="inline-flex rounded-full bg-detective-yellow-100 px-4 py-2 font-display text-sm font-semibold text-detective-orange-600">WHY IP2KIDS?</p><h1 className="mt-6 font-display text-4xl font-bold text-detective-blue-900 sm:text-5xl">Children are already creators.</h1><p className="mt-6 text-lg text-detective-blue-700/85">Every time a child draws, writes, invents, designs or dreams up a solution, they are creating. IP2Kids makes intellectual property easy to discover through stories, mysteries, games and challenges.</p><p className="mt-5 rounded-3xl border-2 border-detective-yellow-300 bg-detective-yellow-100 px-5 py-4 font-display text-xl font-bold text-detective-blue-900">“What we create has value.”</p></div><Image src={questyArt.detective} alt="Questy ready to investigate creative ideas" priority sizes="(min-width:640px) 380px,260px" className="mx-auto h-[300px] w-auto object-contain sm:h-[380px]"/></Container></section>
<section className="bg-detective-yellow-50 py-16 sm:py-20"><Container><div className="mx-auto max-w-4xl rounded-[2.5rem] border-2 border-detective-yellow-300 bg-white p-8 text-center shadow-sm sm:p-12"><p className="font-display text-sm font-bold uppercase tracking-[.2em] text-detective-orange-600">OUR MISSION</p><h2 className="mt-4 font-display text-3xl font-bold text-detective-blue-900 sm:text-4xl">Learning about ideas should be free.</h2><p className="mx-auto mt-5 max-w-3xl text-lg leading-relaxed text-detective-blue-700/85">IP2Kids began as a personal educational initiative with a simple purpose: to make intellectual property understandable and enjoyable for young learners. Through Little IP Detectives, children investigate mysteries, solve problems and discover how creativity, brands, inventions and designs connect with everyday life.</p><p className="mx-auto mt-5 max-w-3xl font-display text-xl font-bold text-detective-blue-900">All 15 learning worlds are free to explore. No subscription. No paid learning levels.</p><p className="mx-auto mt-4 max-w-3xl text-sm text-detective-blue-700/75">IP2Kids is an independent educational initiative designed to complement, not replace, formal classroom learning. Its content is educational and is not legal advice.</p></div></Container></section>
<section className="bg-detective-blue-50/70 py-16"><Container><SectionHeading eyebrow="Why it matters" title="Why Should Kids Learn About IP?" subtitle="The ideas behind intellectual property are already part of a child’s everyday world."/><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{whyIpMatters.map(card=><article key={card.title} className={`rounded-3xl border-2 p-6 shadow-sm ${card.surface}`}><span className="text-4xl">{card.emoji}</span><h3 className="mt-4 font-display text-2xl font-bold text-detective-blue-900">{card.title}</h3><p className="mt-2 font-display font-semibold text-detective-orange-600">“{card.statement}”</p><p className="mt-3 text-sm text-detective-blue-700/85">{card.description}</p></article>)}</div></Container></section>
<section className="py-16"><Container><SectionHeading eyebrow="Everyday clues" title="They already see IP every day."/><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{everydayIp.map(item=><article key={item.kind} className="rounded-3xl border-2 border-detective-blue-100 bg-white p-5 text-center"><span className="text-4xl">{item.emoji}</span><p className="mt-3 text-xs font-bold tracking-widest text-detective-blue-500">{item.clue}</p><p className="mt-2 font-display text-2xl font-bold text-detective-orange-500">→ {item.kind}</p><p className="mt-3 text-sm text-detective-blue-700/85">{item.description}</p></article>)}</div></Container></section>
<section className="bg-detective-blue-900 py-16 text-white"><Container><p className="font-display text-sm font-semibold uppercase tracking-[.2em] text-detective-yellow-300">Our philosophy</p><h2 className="mt-4 max-w-3xl font-display text-3xl font-bold sm:text-5xl">We don&apos;t teach children IP law. We teach them to think like creators.</h2><div className="mt-8 grid gap-3 sm:grid-cols-2">{creatorQuestions.map(q=><p key={q} className="rounded-2xl bg-white/10 px-4 py-3 font-display font-semibold">🔍 {q}</p>)}</div></Container></section>
<section className="py-16"><Container><SectionHeading eyebrow="Our promise" title="The IP2Kids Learning Promise"/><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{learningPromise.map(item=><article key={item.title} className={`rounded-3xl p-6 shadow-lg ${item.tone}`}><h3 className="font-display text-2xl font-bold">{item.title}</h3><p className="mt-4 text-sm">{item.description}</p></article>)}</div></Container></section>
<section className="bg-detective-blue-50/70 py-16"><Container><SectionHeading eyebrow="The basics" title="Four Big Ideas to Discover" subtitle="These are introductory ideas, not legal advice. Different creations may be protected in different ways."/><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{fourBigIdeas.map(item=><article key={item.title} className={`rounded-3xl border-2 p-6 ${item.tone}`}><span className="text-4xl">{item.emoji}</span><h3 className="mt-4 font-display text-2xl font-bold text-detective-blue-900">{item.title}</h3><p className="mt-3 text-sm text-detective-blue-700/85">{item.description}</p></article>)}</div></Container></section>
<section className="py-16"><Container className="grid items-center gap-10 lg:grid-cols-2"><div><p className="font-display text-sm font-semibold uppercase tracking-[.2em] text-detective-orange-500">Learning through adventure</p><h2 className="mt-4 font-display text-3xl font-bold text-detective-blue-900">15 Worlds. One Big Adventure.</h2><p className="mt-5 text-lg text-detective-blue-700/85">Mysteries, stories, quizzes, puzzles, colouring activities, challenges and rewards help children learn by doing.</p></div><Image src={questyArt.celebrating} alt="Questy celebrating" sizes="300px" className="mx-auto h-[280px] w-auto object-contain"/></Container></section>
<CallToAction title="Ready to Become a Little IP Detective?" subtitle="All 15 learning worlds are free. Join Questy and start investigating." buttonLabel="Start Free Adventure" buttonHref="/#journey"/>
</main><SiteFooter/></>}
