"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, Check, ChevronRight, RotateCcw, Sparkles, Star } from "lucide-react";
import { adventureContent, ultimateIpChallenge, type AdventureQuestion, type AdventureScene } from "@/lib/adventures/adventure-content";
import { playCelebrationSound } from "@/lib/audio";
import type { World } from "@/lib/worlds";

type Step = "story" | "clues" | "discovery" | "mission" | "reward" | "file" | "ultimate";

const steps = [
  { id: "story", label: "Story", emoji: "📖" },
  { id: "clues", label: "Find Clues", emoji: "🔎" },
  { id: "discovery", label: "Discovery", emoji: "💡" },
  { id: "mission", label: "Mission", emoji: "🎮" },
  { id: "reward", label: "Reward", emoji: "🎁" },
  { id: "file", label: "Case File", emoji: "📋" },
] as const;

const primary = "inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-gradient-to-r from-blue-600 to-sky-500 px-5 py-2.5 text-sm font-display font-bold text-white shadow-md shadow-blue-100 transition hover:-translate-y-0.5 sm:min-h-12 sm:px-7 sm:py-3 sm:text-base";
const secondary = "inline-flex min-h-11 items-center justify-center gap-2 rounded-full border-2 border-blue-200 bg-white px-5 py-2.5 text-sm font-display font-bold text-blue-900 transition hover:border-blue-400 sm:min-h-12 sm:px-6 sm:py-3 sm:text-base";

function stepIndex(step: Step) {
  if (step === "ultimate") return 5;
  return Math.max(0, steps.findIndex((item) => item.id === step));
}

function AdventureRail({ step }: { step: Step }) {
  const active = stepIndex(step);
  return <div className="rounded-2xl border border-white/50 bg-white/95 px-2 py-2 shadow-lg backdrop-blur sm:rounded-[1.6rem] sm:px-4 sm:py-3">
    <div className="flex items-start justify-between gap-0.5 overflow-x-auto">{steps.map((item,index)=>{const isActive=index===active;const isDone=index<active;return <div key={item.id} className="flex min-w-[58px] flex-1 items-start sm:min-w-[78px]"><div className="flex flex-1 flex-col items-center text-center"><div className={`grid h-7 w-7 place-items-center rounded-full border font-display text-[10px] font-black sm:h-9 sm:w-9 sm:border-2 sm:text-xs ${isActive?"border-orange-300 bg-orange-500 text-white":isDone?"border-green-300 bg-green-500 text-white":"border-sky-200 bg-sky-100 text-blue-700"}`}>{isDone?<Check className="h-3.5 w-3.5 sm:h-4 sm:w-4"/>:index+1}</div><div className="mt-0.5 text-sm sm:mt-1 sm:text-lg">{item.emoji}</div><p className={`mt-0.5 text-[8px] font-extrabold leading-[1.05] sm:text-[11px] ${isActive?"text-blue-950":"text-blue-700"}`}>{item.label}</p></div>{index<steps.length-1&&<ChevronRight className="mt-3 hidden h-4 w-4 shrink-0 text-sky-400 sm:block"/>}</div>})}</div>
  </div>;
}

function StoryArt({ scene }: { scene: AdventureScene }) {
  if (scene.image) return <picture><source media="(orientation: portrait)" srcSet={scene.image.portrait}/><Image src={scene.image.landscape} alt={scene.title} width={1672} height={941} sizes="(max-width: 1024px) 100vw, 900px" className="h-auto w-full rounded-xl object-contain sm:rounded-2xl"/></picture>;
  return <div className="grid min-h-[190px] place-items-center rounded-xl bg-gradient-to-br from-sky-100 via-white to-yellow-100 p-4 text-center sm:min-h-[260px] sm:rounded-2xl sm:p-7"><div><div className="text-5xl leading-relaxed sm:text-7xl">{scene.art}</div><p className="mt-2 font-display text-base font-bold text-blue-900 sm:mt-4 sm:text-lg">{scene.title}</p></div></div>;
}

function StoryCard({scene,sceneNumber}:{scene:AdventureScene;sceneNumber:number}) {
  return <section className="overflow-hidden rounded-2xl border-2 border-sky-100 bg-white shadow-lg sm:rounded-[2rem] sm:shadow-xl"><div className="p-3.5 sm:p-6"><div className="inline-flex items-center gap-1.5 rounded-full bg-sky-50 px-3 py-1.5 font-display text-[11px] font-bold text-blue-900 sm:text-sm">📖 Scene {sceneNumber} of 4</div><h3 className="mt-2 font-display text-xl font-black tracking-tight text-blue-950 sm:mt-3 sm:text-3xl">{scene.title}</h3><p className="mt-1.5 text-sm leading-relaxed text-blue-900 sm:mt-2 sm:text-base lg:text-lg">{scene.text}</p></div><div className="px-2.5 sm:px-5"><StoryArt scene={scene}/></div><div className="m-3 flex gap-2 rounded-xl bg-gradient-to-r from-amber-50 to-orange-50 p-3 text-sm text-blue-900 sm:m-5 sm:gap-3 sm:rounded-2xl sm:p-4 sm:text-base"><div className="text-xl sm:text-2xl">🐱</div><p className="self-center leading-relaxed"><strong className="font-display">Questy:</strong> Look carefully. Every scene has a clue!</p></div></section>;
}

function StoryGuide({scene,onBack,onNext}:{scene:number;onBack:()=>void;onNext:()=>void}) {
  const spot = ["Who created each item?","What did each creator make?","What changed in the mystery?","Which clues solve the case?"][scene];
  return <aside className="hidden lg:block"><div className="sticky top-24 rounded-[2rem] border-2 border-sky-100 bg-white p-5 shadow-xl"><div className="flex items-center justify-between"><h3 className="font-display text-xl font-black text-blue-950">🔍 Story Guide</h3><span className="rounded-full bg-sky-100 px-3 py-1 text-sm font-bold text-blue-800">{scene+1}/4</span></div><div className="mt-4 rounded-2xl bg-sky-50 p-4"><p className="text-xs font-black uppercase tracking-wider text-orange-600">Look for</p><p className="mt-1 font-display text-base font-bold leading-snug text-blue-950">{spot}</p></div><div className="mt-4 grid grid-cols-4 gap-2">{[0,1,2,3].map(n=><div key={n} className={`h-2 rounded-full ${n<=scene?"bg-orange-400":"bg-sky-100"}`}/>)}</div><p className="mt-4 text-sm leading-relaxed text-blue-700">Finish all four scenes first. Then the clue questions will appear one at a time.</p><div className="mt-5 flex gap-2"><button disabled={scene===0} onClick={onBack} className={`${secondary} flex-1 disabled:invisible`}><ArrowLeft className="h-4 w-4"/>Back</button><button onClick={onNext} className={`${primary} flex-1`}>{scene===3?"Clues":"Next"}<ArrowRight className="h-4 w-4"/></button></div></div></aside>;
}

function MobileStoryNav({scene,onBack,onNext}:{scene:number;onBack:()=>void;onNext:()=>void}) {
  return <div className="mt-3 flex gap-2 lg:hidden"><button disabled={scene===0} onClick={onBack} className={`${secondary} flex-1 disabled:invisible`}><ArrowLeft className="h-4 w-4"/>Back</button><button onClick={onNext} className={`${primary} flex-1`}>{scene===3?"Find Clues":"Next Scene"}<ArrowRight className="h-4 w-4"/></button></div>;
}

function Question({q,n,total,onNext}:{q:AdventureQuestion;n:number;total:number;onNext:()=>void}) {
  const[selected,setSelected]=useState<number|null>(null);const[ok,setOk]=useState(false);const[message,setMessage]=useState("");
  function choose(index:number){if(ok)return;setSelected(index);if(index===q.correct){setOk(true);setMessage(q.feedback)}else setMessage("Almost! Check the story clue and try again.")}
  return <section className="rounded-2xl border-2 border-sky-100 bg-white p-4 shadow-lg sm:rounded-[2rem] sm:p-7 sm:shadow-xl"><div className="flex items-center justify-between gap-3"><h3 className="font-display text-xl font-black text-blue-950 sm:text-2xl">🔎 Find the Clues</h3><span className="rounded-full bg-sky-100 px-3 py-1.5 text-xs font-bold text-blue-800 sm:px-4 sm:py-2 sm:text-sm">{n} / {total}</span></div><div className="mt-3 rounded-xl bg-gradient-to-r from-sky-50 to-blue-50 p-3.5 sm:mt-5 sm:rounded-2xl sm:p-5"><p className="font-display text-base font-black leading-snug text-blue-950 sm:text-xl">{q.prompt}</p></div><div className="mt-3 grid gap-2 sm:mt-4 sm:gap-3">{q.options.map((option,index)=><button key={option} disabled={ok} onClick={()=>choose(index)} className={`flex min-h-12 items-center rounded-xl border-2 px-3 py-2.5 text-left text-sm font-semibold transition sm:min-h-14 sm:rounded-2xl sm:px-4 sm:py-3 sm:text-base ${ok&&index===q.correct?"border-green-400 bg-green-50 text-green-900":selected===index&&!ok?"border-amber-400 bg-amber-50":"border-sky-100 bg-white text-blue-950 hover:border-blue-300 hover:bg-sky-50"}`}><span className="mr-2.5 grid h-8 w-8 shrink-0 place-items-center rounded-full bg-blue-500 font-display text-xs font-black text-white sm:mr-3 sm:h-9 sm:w-9 sm:text-sm">{String.fromCharCode(65+index)}</span><span className="flex-1">{option}</span>{ok&&index===q.correct&&<Check className="h-5 w-5 text-green-600 sm:h-6 sm:w-6"/>}</button>)}</div>{message&&<div className={`mt-3 flex gap-2 rounded-xl p-3 text-sm sm:mt-5 sm:gap-3 sm:rounded-2xl sm:p-4 sm:text-base ${ok?"bg-amber-50 text-green-900":"bg-yellow-50 text-blue-900"}`}><div className="text-2xl">🐱</div><p><strong className="font-display">{ok?"Great job!":"Questy:"}</strong><br/>{message}</p></div>}{ok&&<button onClick={onNext} className={`${primary} mt-4 w-full sm:mt-5`}>{n===total?"See Questy's Discovery":"Next Question"}<ArrowRight className="h-4 w-4"/></button>}</section>;
}

function Mission({title,body,prompt,choices,correct,onDone}:{title:string;body:string;prompt:string;choices:{label:string;emoji:string}[];correct:number[];onDone:()=>void}) {
  const[selected,setSelected]=useState<number[]>([]);const[solved,setSolved]=useState(false);const[message,setMessage]=useState("");const key=useMemo(()=>[...correct].sort((a,b)=>a-b).join(","),[correct]);
  function toggle(index:number){if(solved)return;if(correct.length===1)setSelected([index]);else setSelected(current=>current.includes(index)?current.filter(x=>x!==index):[...current,index]);setMessage("")}
  function check(){if([...selected].sort((a,b)=>a-b).join(",")===key){setSolved(true);setMessage("Mission complete! You used the clue perfectly.")}else setMessage("Good try! Check the clue once more and change your choices.")}
  return <section className="rounded-2xl border-2 border-purple-100 bg-white p-4 shadow-lg sm:rounded-[2rem] sm:p-8 sm:shadow-xl"><div className="inline-flex rounded-full bg-purple-100 px-3 py-1.5 text-xs font-display font-black text-purple-800 sm:px-4 sm:py-2 sm:text-sm">🎮 MINI MISSION</div><h3 className="mt-3 font-display text-xl font-black text-blue-950 sm:mt-4 sm:text-3xl">{title}</h3><p className="mt-2 text-sm text-blue-900 sm:mt-3 sm:text-lg">{body}</p><p className="mt-4 rounded-xl bg-purple-50 p-3.5 font-display text-base font-black text-blue-950 sm:mt-6 sm:rounded-2xl sm:p-5 sm:text-xl">{prompt}</p><div className="mt-4 grid gap-2 sm:mt-5 sm:grid-cols-2 sm:gap-3">{choices.map((choice,index)=><button key={choice.label} onClick={()=>toggle(index)} className={`min-h-14 rounded-xl border-2 p-3 text-left text-sm transition sm:min-h-20 sm:rounded-2xl sm:p-4 sm:text-base ${selected.includes(index)?"border-purple-500 bg-purple-100":"border-purple-100 bg-white hover:bg-purple-50"}`}><span className="mr-2 text-xl sm:mr-3 sm:text-2xl">{choice.emoji}</span><span className="font-semibold">{choice.label}</span></button>)}</div>{message&&<p className={`mt-4 rounded-xl p-3 text-sm font-display font-bold sm:mt-5 sm:rounded-2xl sm:p-4 sm:text-base ${solved?"bg-green-100 text-green-800":"bg-yellow-100 text-blue-900"}`}>🐱 Questy: {message}</p>}<div className="mt-4 sm:mt-6">{solved?<button onClick={onDone} className={primary}>Unlock My Reward<Sparkles className="h-4 w-4"/></button>:<button onClick={check} disabled={!selected.length} className={`${primary} disabled:opacity-50`}>Check My Mission</button>}</div></section>;
}

function Ultimate({onFinish}:{onFinish:(score:number)=>void}) {
  const[index,setIndex]=useState(0);const[score,setScore]=useState(0);const[ok,setOk]=useState(false);const[message,setMessage]=useState("");const q=ultimateIpChallenge[index];
  function choose(answer:number){if(ok)return;if(answer===q.correct){setOk(true);setScore(value=>value+1);setMessage(q.feedback)}else setMessage("Nice try! Look for the IP clue and try again.")}
  function next(){if(index===9){onFinish(score);return}setIndex(value=>value+1);setOk(false);setMessage("")}
  return <section className="rounded-2xl border-2 border-yellow-300 bg-white p-4 shadow-lg sm:rounded-[2rem] sm:p-8 sm:shadow-xl"><p className="text-xs font-display font-black text-orange-600 sm:text-sm">🏆 QUESTY&apos;S ULTIMATE IP CHALLENGE</p><h3 className="mt-2 font-display text-xl font-black text-blue-950 sm:mt-3 sm:text-2xl">Final mystery {index+1} of 10 · ⭐ {score}</h3><p className="mt-3 text-base font-semibold text-blue-950 sm:mt-5 sm:text-xl">{q.prompt}</p><div className="mt-4 grid gap-2 sm:mt-6 sm:gap-3">{q.options.map((option,answer)=><button key={option} disabled={ok} onClick={()=>choose(answer)} className={`min-h-12 rounded-xl border-2 px-4 py-2.5 text-left text-sm font-semibold sm:min-h-14 sm:rounded-2xl sm:px-5 sm:py-3 sm:text-base ${ok&&answer===q.correct?"border-green-500 bg-green-50":"border-sky-100 bg-white hover:border-blue-300"}`}>{String.fromCharCode(65+answer)}. {option}</button>)}</div>{message&&<p className={`mt-4 rounded-xl p-3 text-sm font-semibold sm:mt-5 sm:rounded-2xl sm:p-4 sm:text-base ${ok?"bg-green-100":"bg-yellow-100"}`}>🐱 Questy: {message}</p>}{ok&&<button onClick={next} className={`${primary} mt-4 sm:mt-6`}>{index===9?"See My Celebration":"Next Mystery"}<ArrowRight className="h-4 w-4"/></button>}</section>;
}

export function AdventureExperience({world,isCompleted,onComplete,onNextWorld}:{world:World;isCompleted:boolean;onComplete:(correct:number,total:number)=>void;onNextWorld:(id:number)=>void}) {
  const content=adventureContent.find(item=>item.id===world.id)??adventureContent[0];const[step,setStep]=useState<Step>("story");const[scene,setScene]=useState(0);const[question,setQuestion]=useState(0);const[finalScore,setFinalScore]=useState<number|null>(null);const sent=useRef(false);
  useEffect(()=>{setStep("story");setScene(0);setQuestion(0);setFinalScore(null);sent.current=false},[world.id]);
  function finish(){if(!isCompleted&&!sent.current){sent.current=true;onComplete(5,5);playCelebrationSound()}setStep("reward")}
  function finishUltimate(score:number){setFinalScore(score);playCelebrationSound()}
  const nextWorld=world.id<15?world.id+1:null;const finalMessage=finalScore===10?"Amazing! Master Idea Adventurer!":(finalScore??0)>=7?"Brilliant Idea Explorer!":(finalScore??0)>=4?"Great investigating!":"Every great explorer learns by trying again!";
  const nextScene=()=>{if(scene===3)setStep("clues");else setScene(value=>value+1)};
  const backScene=()=>setScene(value=>Math.max(0,value-1));
  return <div className="mt-4 overflow-hidden rounded-2xl border border-sky-100 bg-gradient-to-b from-sky-50 via-white to-amber-50 shadow-lg sm:mt-8 sm:rounded-[2.2rem] sm:shadow-2xl"><header className="bg-gradient-to-r from-blue-600 via-sky-500 to-blue-500 p-3 sm:p-6"><div className="grid items-center gap-3 lg:grid-cols-[0.72fr_1.28fr] lg:gap-6"><div className="flex items-center gap-3 text-white sm:gap-5"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-full border-[3px] border-yellow-300 bg-gradient-to-br from-yellow-300 to-orange-400 shadow-md sm:h-20 sm:w-20 sm:border-[5px]"><div className="text-center"><div className="text-sm sm:text-xl">{content.icon}</div><div className="font-display text-xl font-black leading-none sm:text-2xl">{world.id}</div></div></div><div><p className="font-display text-[11px] font-black text-yellow-200 sm:text-sm">Adventure {world.id}</p><h2 className="font-display text-2xl font-black tracking-tight drop-shadow-sm sm:text-4xl">{content.title}</h2><p className="mt-0.5 text-xs font-semibold text-white/95 sm:mt-1 sm:text-base">{content.subtitle}</p></div></div><AdventureRail step={step}/></div></header><div className="p-2.5 sm:p-5 lg:p-6">
    {step==="story"&&<><div className="grid gap-4 lg:grid-cols-[1.8fr_0.8fr]"><StoryCard scene={content.scenes[scene]} sceneNumber={scene+1}/><StoryGuide scene={scene} onBack={backScene} onNext={nextScene}/></div><MobileStoryNav scene={scene} onBack={backScene} onNext={nextScene}/></>}
    {step==="clues"&&<div className="mx-auto max-w-3xl"><Question key={`${world.id}-${question}`} q={content.questions[question]} n={question+1} total={5} onNext={()=>{if(question===4)setStep("discovery");else setQuestion(value=>value+1)}}/></div>}
    {step==="discovery"&&<section className="mx-auto max-w-4xl rounded-2xl border-2 border-yellow-200 bg-white p-4 shadow-lg sm:rounded-[2rem] sm:p-7 sm:shadow-xl"><div className="text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-yellow-100 text-2xl sm:h-16 sm:w-16 sm:text-4xl">💡</div><p className="mt-2 text-xs font-display font-black uppercase tracking-wider text-orange-600 sm:mt-3 sm:text-sm">Questy&apos;s Discovery</p><h3 className="mt-1 font-display text-xl font-black text-blue-950 sm:mt-2 sm:text-3xl">You found the idea!</h3></div><div className="mt-4 grid gap-2 sm:mt-6 sm:grid-cols-3 sm:gap-4">{content.discovery.map(item=><article key={item.title} className="rounded-xl border-2 border-sky-100 bg-sky-50 p-3.5 sm:rounded-3xl sm:bg-gradient-to-b sm:from-sky-50 sm:to-white sm:p-5"><Sparkles className="h-5 w-5 text-orange-500 sm:h-6 sm:w-6"/><h4 className="mt-2 font-display text-base font-black text-blue-950 sm:mt-3 sm:text-lg">{item.title}</h4><p className="mt-1 text-sm text-blue-900 sm:mt-2 sm:text-base">{item.body}</p></article>)}</div><div className="mt-5 text-center sm:mt-7"><button onClick={()=>setStep("mission")} className={primary}>Try the Mini Mission<ArrowRight className="h-4 w-4"/></button></div></section>}
    {step==="mission"&&<div className="mx-auto max-w-4xl"><Mission title={content.miniMission.title} body={content.miniMission.body} prompt={content.missionPrompt} choices={content.missionChoices} correct={content.missionCorrect} onDone={finish}/></div>}
    {step==="reward"&&<section className="mx-auto max-w-4xl rounded-2xl border-2 border-green-200 bg-white p-5 text-center shadow-lg sm:rounded-[2rem] sm:p-7 sm:shadow-xl"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-gradient-to-br from-yellow-200 to-orange-300 text-4xl shadow-md sm:h-24 sm:w-24 sm:text-6xl">{world.reward.badge}</div><h3 className="mt-3 font-display text-2xl font-black text-blue-950 sm:mt-5 sm:text-4xl">Adventure Complete!</h3><p className="mt-1 text-sm text-blue-900 sm:mt-3 sm:text-lg">You discovered a new idea superpower.</p><div className="mx-auto mt-4 max-w-2xl rounded-2xl bg-amber-50 p-4 sm:mt-6 sm:rounded-3xl sm:p-6"><p className="font-display text-base font-black text-orange-600 sm:text-xl">🎁 Reward Activity</p><p className="mt-2 text-sm text-blue-900 sm:mt-3 sm:text-lg">{content.reward}</p></div><button onClick={()=>setStep("file")} className={`${primary} mt-5 sm:mt-7`}>Open My Case File<ArrowRight className="h-4 w-4"/></button></section>}
    {step==="file"&&<section className="mx-auto max-w-4xl rounded-2xl border-2 border-sky-100 bg-white p-4 shadow-lg sm:rounded-[2rem] sm:p-7 sm:shadow-xl"><div className="flex flex-wrap items-start justify-between gap-2 sm:gap-4"><div><p className="text-xs font-display font-black uppercase tracking-wider text-orange-600 sm:text-sm">📋 Case File #{world.id}</p><h3 className="mt-1 font-display text-xl font-black text-blue-950 sm:mt-2 sm:text-3xl">What I Discovered</h3></div><div className="rounded-full bg-green-100 px-3 py-1.5 text-xs font-display font-black text-green-800 sm:px-4 sm:py-2 sm:text-sm">✓ CASE SOLVED</div></div><div className="mt-4 grid gap-2 sm:mt-6 sm:grid-cols-2 sm:gap-3">{content.caseFile.map(item=><div key={item} className="flex gap-2 rounded-xl bg-sky-50 p-3 text-sm text-blue-950 sm:gap-3 sm:rounded-2xl sm:p-4 sm:text-base"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-green-500 text-white"><Check className="h-3.5 w-3.5"/></span>{item}</div>)}</div><div className="mt-5 flex flex-wrap gap-2 sm:mt-7 sm:gap-3">{world.id===15?<button onClick={()=>setStep("ultimate")} className={primary}>Start Final Quest 🏆</button>:nextWorld&&<button onClick={()=>onNextWorld(nextWorld)} className={primary}>Next Adventure {nextWorld}<ArrowRight className="h-4 w-4"/></button>}<button onClick={()=>{setScene(0);setQuestion(0);setStep("story")}} className={secondary}><RotateCcw className="h-4 w-4"/>Replay</button></div></section>}
    {step==="ultimate"&&finalScore===null&&<div className="mx-auto max-w-4xl"><Ultimate onFinish={finishUltimate}/></div>}
    {step==="ultimate"&&finalScore!==null&&<section className="mx-auto max-w-4xl rounded-2xl border-2 border-yellow-300 bg-white p-5 text-center shadow-lg sm:rounded-[2rem] sm:p-10 sm:shadow-xl"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-yellow-100 text-4xl sm:h-24 sm:w-24 sm:text-5xl">🏆</div><h3 className="mt-3 font-display text-2xl font-black text-blue-950 sm:mt-5 sm:text-4xl">{finalMessage}</h3><p className="mt-2 text-base font-bold text-blue-900 sm:mt-3 sm:text-xl">You solved {finalScore} of 10 final mysteries.</p><div className="mx-auto mt-4 flex max-w-md justify-center gap-1 sm:mt-5">{Array.from({length:10}).map((_,index)=><Star key={index} className={`h-5 w-5 sm:h-6 sm:w-6 ${index<finalScore?"fill-yellow-400 text-yellow-400":"text-slate-200"}`}/>)}</div><p className="mx-auto mt-4 max-w-2xl text-sm text-blue-900 sm:mt-6 sm:text-lg">You have completed all 15 Idea Adventures. Keep noticing, creating and respecting ideas wherever you go.</p><div className="mt-5 flex flex-wrap justify-center gap-2 sm:mt-7 sm:gap-3"><Link href="/books" className={primary}><BookOpen className="h-5 w-5"/>Book Corner</Link><button onClick={()=>{setFinalScore(null);setStep("ultimate")}} className={secondary}><RotateCcw className="h-4 w-4"/>Try Again</button></div></section>}
  </div></div>;
}
