"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, Check, RotateCcw, Sparkles } from "lucide-react";
import { adventureContent, ultimateIpChallenge, type AdventureQuestion, type AdventureScene } from "@/lib/adventures/adventure-content";
import { playCelebrationSound } from "@/lib/audio";
import { worldTheme, type World } from "@/lib/worlds";

const primary="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-detective-orange-500 px-6 py-3 font-display font-bold text-white shadow-sm transition hover:bg-detective-orange-600";
const secondary="inline-flex min-h-12 items-center justify-center gap-2 rounded-full border-2 border-detective-blue-200 bg-white px-6 py-3 font-display font-bold text-detective-blue-800";
type Step="story"|"clues"|"discovery"|"mission"|"reward"|"file"|"ultimate";
const steps=[{id:"story",label:"Story",emoji:"📖"},{id:"clues",label:"Find the Clues",emoji:"🔎"},{id:"discovery",label:"Questy's Discovery",emoji:"💡"},{id:"mission",label:"Mini Mission",emoji:"🎯"},{id:"reward",label:"Reward",emoji:"🎁"},{id:"file",label:"Case File",emoji:"📋"}] as const;

function StepBar({step}:{step:Step}){const active=step==="ultimate"?5:Math.max(0,steps.findIndex(x=>x.id===step));return <div className="grid grid-cols-3 gap-2 sm:grid-cols-6">{steps.map((x,i)=><div key={x.id} className={`rounded-2xl border-2 px-2 py-3 text-center text-xs font-bold sm:text-sm ${i===active?"border-detective-orange-400 bg-detective-orange-50 text-detective-orange-700":i<active?"border-green-200 bg-green-50 text-green-700":"border-detective-blue-100 bg-white text-detective-blue-500"}`}><span className="mr-1">{i<active?"✓":x.emoji}</span>{x.label}</div>)}</div>}

function StoryArt({scene}:{scene:AdventureScene}){if(scene.image)return <picture><source media="(orientation: portrait)" srcSet={scene.image.portrait}/><Image src={scene.image.landscape} alt={scene.title} width={1672} height={941} sizes="(max-width:1024px) 100vw,896px" className="mt-5 h-auto w-full rounded-3xl object-contain shadow-md"/></picture>;return <div className="mt-5 grid min-h-[220px] place-items-center rounded-3xl border-2 border-detective-blue-100 bg-gradient-to-br from-sky-100 via-white to-detective-yellow-100 p-8 text-center sm:min-h-[280px]"><div><div className="text-5xl leading-relaxed sm:text-7xl">{scene.art}</div><p className="mt-5 font-display text-lg font-bold text-detective-blue-800">Imagine the scene with Questy as you read.</p></div></div>}

function Question({q,n,total,onNext}:{q:AdventureQuestion;n:number;total:number;onNext:()=>void}){const[selected,setSelected]=useState<number|null>(null);const[ok,setOk]=useState(false);const[msg,setMsg]=useState("");function choose(i:number){if(ok)return;setSelected(i);if(i===q.correct){setOk(true);setMsg(q.feedback)}else setMsg("Almost! Look at the story clue again and try another answer.")}return <section className="rounded-[2rem] border-2 border-detective-blue-100 bg-white p-5 shadow-lg sm:p-8"><div className="flex justify-between gap-3"><p className="font-display font-bold text-detective-orange-600">🔎 FIND THE CLUES</p><span className="rounded-full bg-detective-yellow-100 px-3 py-1 font-bold">{n}/{total}</span></div><h3 className="mt-4 font-display text-2xl font-bold text-detective-blue-900">{q.prompt}</h3><div className="mt-6 grid gap-3">{q.options.map((o,i)=><button key={o} disabled={ok} onClick={()=>choose(i)} className={`min-h-14 rounded-2xl border-2 px-5 py-3 text-left font-semibold ${ok&&i===q.correct?"border-green-500 bg-green-50":selected===i&&!ok?"border-amber-400 bg-amber-50":"border-detective-blue-100 bg-sky-50 hover:border-detective-orange-300"}`}><span className="mr-3 inline-grid h-8 w-8 place-items-center rounded-full bg-white font-bold">{String.fromCharCode(65+i)}</span>{o}{ok&&i===q.correct&&<Check className="ml-2 inline h-5 w-5 text-green-600"/>}</button>)}</div>{msg&&<p className={`mt-5 rounded-2xl p-4 font-display font-semibold ${ok?"bg-green-50 text-green-800":"bg-detective-yellow-100"}`}>🐱 Questy: {msg}</p>}{ok&&<button onClick={onNext} className={`${primary} mt-6`}>{n===total?"See Questy's Discovery":"Next clue"}<ArrowRight className="h-4 w-4"/></button>}</section>}

function Mission({title,body,prompt,choices,correct,onDone}:{title:string;body:string;prompt:string;choices:{label:string;emoji:string}[];correct:number[];onDone:()=>void}){const[selected,setSelected]=useState<number[]>([]);const[solved,setSolved]=useState(false);const[msg,setMsg]=useState("");const key=useMemo(()=>[...correct].sort((a,b)=>a-b).join(","),[correct]);function toggle(i:number){if(solved)return;if(correct.length===1)setSelected([i]);else setSelected(c=>c.includes(i)?c.filter(x=>x!==i):[...c,i]);setMsg("")}function check(){if([...selected].sort((a,b)=>a-b).join(",")===key){setSolved(true);setMsg("Mission complete! You used the clue perfectly.")}else setMsg("Good try! Check the clue once more and change your choices.")}return <section className="rounded-[2rem] border-2 border-purple-200 bg-gradient-to-br from-purple-50 via-white to-pink-50 p-5 shadow-lg sm:p-8"><p className="font-display font-bold text-purple-700">🎯 MINI MISSION</p><h3 className="mt-2 font-display text-3xl font-bold">{title}</h3><p className="mt-3 text-lg">{body}</p><p className="mt-6 rounded-2xl bg-white p-4 font-display text-lg font-bold">{prompt}</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{choices.map((c,i)=><button key={c.label} onClick={()=>toggle(i)} className={`min-h-20 rounded-2xl border-2 p-4 text-left ${selected.includes(i)?"border-purple-500 bg-purple-100":"border-purple-100 bg-white"}`}><span className="mr-3 text-2xl">{c.emoji}</span><span className="font-semibold">{c.label}</span></button>)}</div>{msg&&<p className={`mt-5 rounded-2xl p-4 font-display font-semibold ${solved?"bg-green-100 text-green-800":"bg-detective-yellow-100"}`}>🐱 Questy: {msg}</p>}<div className="mt-6">{solved?<button onClick={onDone} className={primary}>Unlock my reward <Sparkles className="h-4 w-4"/></button>:<button onClick={check} disabled={!selected.length} className={`${primary} disabled:opacity-50`}>Check my mission</button>}</div></section>}

function Ultimate({onFinish}:{onFinish:(score:number)=>void}){const[index,setIndex]=useState(0);const[score,setScore]=useState(0);const[ok,setOk]=useState(false);const[msg,setMsg]=useState("");const q=ultimateIpChallenge[index];function choose(i:number){if(ok)return;if(i===q.correct){setOk(true);setScore(s=>s+1);setMsg(q.feedback)}else setMsg("Nice try! Look for the IP clue and try again.")}function next(){if(index===9){onFinish(score);return}setIndex(i=>i+1);setOk(false);setMsg("")}return <section className="rounded-[2rem] border-2 border-detective-yellow-300 bg-gradient-to-br from-yellow-50 via-white to-sky-50 p-5 shadow-xl sm:p-8"><p className="font-display font-bold text-detective-orange-600">🏆 QUESTY'S ULTIMATE IP CHALLENGE</p><h3 className="mt-3 font-display text-2xl font-bold">Final mystery {index+1} of 10 · ⭐ {score}</h3><p className="mt-5 text-xl font-semibold">{q.prompt}</p><div className="mt-6 grid gap-3">{q.options.map((o,i)=><button key={o} disabled={ok} onClick={()=>choose(i)} className={`min-h-14 rounded-2xl border-2 px-5 py-3 text-left font-semibold ${ok&&i===q.correct?"border-green-500 bg-green-50":"border-detective-blue-100 bg-white"}`}>{String.fromCharCode(65+i)}. {o}</button>)}</div>{msg&&<p className={`mt-5 rounded-2xl p-4 font-semibold ${ok?"bg-green-100":"bg-detective-yellow-100"}`}>🐱 Questy: {msg}</p>}{ok&&<button onClick={next} className={`${primary} mt-6`}>{index===9?"See my celebration":"Next mystery"}<ArrowRight className="h-4 w-4"/></button>}</section>}

export function AdventureExperience({world,isCompleted,onComplete,onNextWorld}:{world:World;isCompleted:boolean;onComplete:(correct:number,total:number)=>void;onNextWorld:(id:number)=>void}){const content=adventureContent.find(x=>x.id===world.id)??adventureContent[0];const theme=worldTheme[world.color];const[step,setStep]=useState<Step>("story");const[scene,setScene]=useState(0);const[q,setQ]=useState(0);const[finalScore,setFinalScore]=useState<number|null>(null);const sent=useRef(false);useEffect(()=>{setStep("story");setScene(0);setQ(0);setFinalScore(null);sent.current=false},[world.id]);function finish(){if(!isCompleted&&!sent.current){sent.current=true;onComplete(5,5);playCelebrationSound()}setStep("reward")}function final(score:number){setFinalScore(score);playCelebrationSound()}const next=world.id<15?world.id+1:null;const finalMsg=finalScore===10?"Amazing! Master Idea Adventurer!":(finalScore??0)>=7?"Brilliant Idea Explorer!":(finalScore??0)>=4?"Great investigating!":"Every great explorer learns by trying again!";return <div className="mt-8 space-y-6 border-t-2 border-dashed border-detective-blue-200 pt-8"><div className={`rounded-[2rem] bg-gradient-to-r ${theme.gradient} p-1 shadow-lg`}><div className="rounded-[1.8rem] bg-white/95 p-5 sm:p-7"><p className="font-display text-sm font-bold uppercase tracking-widest text-detective-orange-600">Adventure {world.id}</p><h2 className="mt-1 font-display text-3xl font-bold text-detective-blue-900 sm:text-4xl">{content.icon} {content.title}</h2><p className="mt-2 text-lg text-detective-blue-700">{content.subtitle}</p><p className="mt-3 inline-block rounded-full bg-detective-yellow-100 px-4 py-2 font-display font-bold">Short story · 5 clues · 1 mission</p><div className="mt-6"><StepBar step={step}/></div></div></div>
{step==="story"&&<section className="rounded-[2rem] border-2 border-detective-blue-100 bg-white p-4 shadow-lg sm:p-7"><p className="font-display font-bold text-detective-orange-600">📖 STORY · SCENE {scene+1} OF 4</p><h3 className="mt-3 font-display text-3xl font-bold">{content.scenes[scene].title}</h3><StoryArt scene={content.scenes[scene]}/><p className="mt-5 rounded-2xl bg-sky-50 p-5 text-lg leading-relaxed">{content.scenes[scene].text}</p><div className="mt-6 flex justify-between gap-3"><button disabled={!scene} onClick={()=>setScene(s=>s-1)} className={`${secondary} disabled:invisible`}><ArrowLeft className="h-4 w-4"/>Back</button><button onClick={()=>scene===3?setStep("clues"):setScene(s=>s+1)} className={primary}>{scene===3?"Find the clues":"Next scene"}<ArrowRight className="h-4 w-4"/></button></div></section>}
{step==="clues"&&<Question key={`${world.id}-${q}`} q={content.questions[q]} n={q+1} total={5} onNext={()=>q===4?setStep("discovery"):setQ(v=>v+1)}/>} 
{step==="discovery"&&<section className="rounded-[2rem] border-2 border-detective-yellow-200 bg-gradient-to-br from-yellow-50 via-white to-sky-50 p-5 shadow-lg sm:p-8"><p className="font-display font-bold text-detective-orange-600">💡 QUESTY'S DISCOVERY</p><h3 className="mt-2 font-display text-3xl font-bold">You found the idea!</h3><div className="mt-6 grid gap-4 sm:grid-cols-3">{content.discovery.map(x=><article key={x.title} className="rounded-3xl border-2 border-detective-blue-100 bg-white p-5"><Sparkles className="h-6 w-6 text-detective-orange-500"/><h4 className="mt-3 font-display text-lg font-bold">{x.title}</h4><p className="mt-2">{x.body}</p></article>)}</div><button onClick={()=>setStep("mission")} className={`${primary} mt-7`}>Try the Mini Mission <ArrowRight className="h-4 w-4"/></button></section>}
{step==="mission"&&<Mission title={content.miniMission.title} body={content.miniMission.body} prompt={content.missionPrompt} choices={content.missionChoices} correct={content.missionCorrect} onDone={finish}/>} 
{step==="reward"&&<section className="rounded-[2rem] border-2 border-green-200 bg-gradient-to-br from-green-50 via-white to-yellow-50 p-7 text-center shadow-xl"><div className="text-6xl">{world.reward.badge}</div><h3 className="mt-4 font-display text-3xl font-bold">Adventure complete!</h3><p className="mt-3 text-lg">You discovered a new idea superpower.</p><div className="mx-auto mt-6 max-w-2xl rounded-3xl bg-white p-6"><p className="font-display text-xl font-bold text-detective-orange-600">🎁 Reward Activity</p><p className="mt-3 text-lg">{content.reward}</p></div><button onClick={()=>setStep("file")} className={`${primary} mt-7`}>Open my Case File <ArrowRight className="h-4 w-4"/></button></section>}
{step==="file"&&<section className="rounded-[2rem] border-2 border-detective-blue-100 bg-white p-6 shadow-lg"><p className="font-display font-bold text-detective-orange-600">📋 CASE FILE #{world.id}</p><h3 className="mt-2 font-display text-3xl font-bold">What I discovered</h3><div className="mt-6 grid gap-3">{content.caseFile.map(x=><div key={x} className="flex gap-3 rounded-2xl bg-green-50 p-4 text-lg"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-green-500 text-white"><Check className="h-4 w-4"/></span>{x}</div>)}</div><div className="mt-7 flex flex-wrap gap-3">{world.id===15?<button onClick={()=>setStep("ultimate")} className={primary}>Start the 10-question Final Quest 🏆</button>:next&&<button onClick={()=>onNextWorld(next)} className={primary}>Next Adventure {next}<ArrowRight className="h-4 w-4"/></button>}<button onClick={()=>{setScene(0);setQ(0);setStep("story")}} className={secondary}><RotateCcw className="h-4 w-4"/>Replay</button></div></section>}
{step==="ultimate"&&finalScore===null&&<Ultimate onFinish={final}/>} 
{step==="ultimate"&&finalScore!==null&&<section className="rounded-[2rem] border-2 border-detective-yellow-300 bg-gradient-to-br from-yellow-100 via-white to-sky-100 p-8 text-center shadow-xl"><div className="text-7xl">🏆</div><h3 className="mt-4 font-display text-4xl font-bold">{finalMsg}</h3><p className="mt-3 text-xl">You solved {finalScore} of 10 final mysteries.</p><p className="mx-auto mt-5 max-w-2xl text-lg">There is no pass or fail. You completed all 15 Idea Adventures. Keep creating, asking questions and exploring.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Link href="/books" className={primary}><BookOpen className="h-5 w-5"/>Visit Book Corner</Link><button onClick={()=>setFinalScore(null)} className={secondary}><RotateCcw className="h-4 w-4"/>Try again</button></div></section>}</div>}
