"use client";

import { useMemo, useState } from "react";
import { RotateCcw, Sparkles } from "lucide-react";

type RewardKind="colour"|"spot"|"match"|"puzzle";
const rewardKinds:Record<number,RewardKind>={1:"colour",2:"spot",3:"puzzle",4:"match",5:"spot",6:"colour",7:"puzzle",8:"match",9:"spot",10:"puzzle",11:"colour",12:"match",13:"spot",14:"puzzle",15:"colour"};
const palette=["#ef4444","#111827","#22c55e","#facc15","#7dd3fc","#a855f7","#f472b6","#92400e","#9ca3af"];
const initialColours=["#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff"];
const themes:Record<number,{title:string;sky:string;ground:string;icons:string[]}>= {
1:{title:"IDEA DAY",sky:"#dff6ff",ground:"#dcfce7",icons:["🎨","🤖","📖","🏷️"]},2:{title:"CREATOR MYSTERY",sky:"#f3e8ff",ground:"#dcfce7",icons:["🖼️","⭐","🔎","✏️"]},3:{title:"CREATE, DON'T COPY",sky:"#ffe4f1",ground:"#fef3c7",icons:["🎨","📖","©️","✨"]},4:{title:"BRAND STREET",sky:"#dff6ff",ground:"#dcfce7",icons:["⭐","🍓","🏪","🏷️"]},5:{title:"LOGO MYSTERY",sky:"#e0f2fe",ground:"#fef3c7",icons:["🔎","⭐","🍓","❓"]},6:{title:"BRAND DETECTIVES",sky:"#e0f2fe",ground:"#dcfce7",icons:["🧃","🏷️","⭐","🔎"]},7:{title:"POWER OF WORDS",sky:"#fff7d6",ground:"#ffe4e6",icons:["💬","✨","🏷️","📣"]},8:{title:"AMAZING INVENTION",sky:"#dbeafe",ground:"#dcfce7",icons:["💡","🤖","⚙️","🔧"]},9:{title:"COPYCAT GADGET",sky:"#fee2e2",ground:"#fef3c7",icons:["🤖","🔎","❓","⚙️"]},10:{title:"WHAT MAKES IT SPECIAL?",sky:"#fef3c7",ground:"#dbeafe",icons:["💡","🧱","📐","⚙️"]},11:{title:"A NEW LOOK",sky:"#fce7f3",ground:"#dbeafe",icons:["🪑","✏️","🎨","✨"]},12:{title:"DESIGN DETECTIVES",sky:"#dff6ff",ground:"#dcfce7",icons:["🧴","🔎","⭐","🎨"]},13:{title:"ALL AROUND US",sky:"#dcfce7",ground:"#fef3c7",icons:["🎨","🤖","🏷️","📖"]},14:{title:"REAL-LIFE CHALLENGES",sky:"#ede9fe",ground:"#fef3c7",icons:["©️","™️","💡","🪑"]},15:{title:"BIG IDEA FESTIVAL",sky:"#dff6ff",ground:"#dcfce7",icons:["🎪","🎨","💡","⭐"]}};
const spotBoards=[["🎨","📖","🤖","🏷️","⭐"],["✏️","📷","🎵","📚","🎬"],["💡","⚙️","🔧","📐","🧪"],["🎒","👟","🪑","💡","⌚"]];
const decoys=["☁️","🍎","⚽","🌳","🥪","🚌","🌈"];
const matchSets:Record<number,{left:string[];right:string[];answer:number[]}>= {4:{left:["🌟 Starzo","🌿 Leafli","🚀 Zoomio","🐾 Pawza"],right:["⭐ Star logo","🍃 Leaf logo","🚀 Rocket logo","🐾 Paw logo"],answer:[0,1,2,3]},8:{left:["🎨 Drawing","📖 Story","📷 Photo","🎵 Song"],right:["👧 Artist","🧒 Writer","👦 Photographer","👧 Musician"],answer:[0,1,2,3]},12:{left:["💡 Lamp","🎒 Backpack","🪑 Chair","⌚ Watch"],right:["〰️ Wavy shade","🔷 Diamond pocket","🌙 Crescent back","⭐ Star face"],answer:[0,1,2,3]}};

function artData(id:number){const t=themes[id]??themes[1];const esc=(s:string)=>s.replace(/&/g,"&amp;");const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="800" height="480" viewBox="0 0 800 480"><rect width="800" height="480" rx="32" fill="${t.sky}"/><circle cx="690" cy="78" r="42" fill="#fde047"/><path d="M0 350 Q130 280 250 350 T500 350 T800 340 V480 H0Z" fill="${t.ground}"/><path d="M70 305V190h170v115M55 190l100-85 100 85" fill="#fff" stroke="#0b3a6e" stroke-width="8" stroke-linejoin="round"/><path d="M500 305V175h210v130M480 175l125-95 125 95" fill="#fff7ed" stroke="#0b3a6e" stroke-width="8" stroke-linejoin="round"/><rect x="285" y="70" width="230" height="74" rx="22" fill="#fff" stroke="#0b3a6e" stroke-width="6"/><text x="400" y="116" text-anchor="middle" font-family="Arial,sans-serif" font-size="26" font-weight="800" fill="#0b3a6e">${esc(t.title)}</text><text x="400" y="265" text-anchor="middle" font-size="72">${t.icons.join("  ")}</text><circle cx="120" cy="365" r="38" fill="#fb923c"/><circle cx="680" cy="365" r="38" fill="#38bdf8"/><text x="120" y="380" text-anchor="middle" font-size="42">🐱</text><text x="680" y="380" text-anchor="middle" font-size="42">🔎</text></svg>`;return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`}
function RewardPicture({id}:{id:number}){return <img src={artData(id)} alt={`${themes[id]?.title??"Idea City"} reward illustration`} className="mb-4 h-auto w-full rounded-2xl border-2 border-sky-100"/>}
function RewardShell({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <section className="mx-auto max-w-4xl rounded-2xl border-2 border-orange-100 bg-white p-4 shadow-lg sm:rounded-[2rem] sm:p-7"><div className="flex items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-orange-100 text-2xl">🎁</div><div><p className="text-[11px] font-display font-black uppercase tracking-wider text-orange-600">Reward Activity</p><h3 className="font-display text-xl font-black text-blue-950 sm:text-3xl">{title}</h3><p className="mt-1 text-sm text-blue-700 sm:text-base">{subtitle}</p></div></div><div className="mt-4 sm:mt-6">{children}</div></section>}
function Finish({onDone}:{onDone:()=>void}){return <div className="mt-5 rounded-2xl bg-green-50 p-4 text-center"><p className="font-display text-lg font-black text-green-800">✨ Reward complete!</p><p className="mt-1 text-sm text-green-800">Great playing. Your Case File is ready.</p><button onClick={onDone} className="mt-3 inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-gradient-to-r from-blue-600 to-sky-500 px-6 py-2.5 text-sm font-display font-bold text-white">Open My Case File <Sparkles className="h-4 w-4"/></button></div>}

function ColourGame({adventureId,onDone}:{adventureId:number;onDone:()=>void}){const[selected,setSelected]=useState(palette[0]);const[fills,setFills]=useState(initialColours);const painted=fills.filter(x=>x!=="#ffffff").length;const fill=(i:number)=>setFills(v=>v.map((c,n)=>n===i?selected:c));const t=themes[adventureId]??themes[1];return <RewardShell title="Colour Quest" subtitle="Choose a colour, then tap the picture regions. There is no wrong colour."><div className="mb-3 rounded-xl bg-sky-50 px-3 py-2 text-center text-xs font-black text-blue-800">{t.title}</div><div className="flex flex-wrap justify-center gap-2">{palette.map(c=><button key={c} onClick={()=>setSelected(c)} className={`h-9 w-9 rounded-full border-4 shadow-sm ${selected===c?"scale-110 border-blue-500":"border-white"}`} style={{backgroundColor:c}}/>)}</div><div className="mx-auto mt-4 max-w-xl rounded-2xl bg-sky-50 p-2"><svg viewBox="0 0 600 390" className="w-full"><rect x="5" y="5" width="590" height="380" rx="28" fill={t.sky} stroke="#0b3a6e" strokeWidth="5"/><path d="M20 300 Q120 235 220 300 T420 300 T580 300 L580 370 L20 370Z" fill={t.ground} stroke="#0b3a6e" strokeWidth="5"/><path onClick={()=>fill(0)} className="cursor-pointer" d="M70 155 L160 80 L250 155 V305 H70Z" fill={fills[0]} stroke="#0b3a6e" strokeWidth="6"/><path onClick={()=>fill(1)} className="cursor-pointer" d="M60 155 L160 65 L260 155Z" fill={fills[1]} stroke="#0b3a6e" strokeWidth="6"/><rect onClick={()=>fill(2)} className="cursor-pointer" x="285" y="145" width="235" height="160" rx="12" fill={fills[2]} stroke="#0b3a6e" strokeWidth="6"/><path onClick={()=>fill(3)} className="cursor-pointer" d="M270 145 L402 65 L535 145Z" fill={fills[3]} stroke="#0b3a6e" strokeWidth="6"/><rect onClick={()=>fill(4)} className="cursor-pointer" x="105" y="210" width="70" height="95" rx="8" fill={fills[4]} stroke="#0b3a6e" strokeWidth="6"/><rect onClick={()=>fill(5)} className="cursor-pointer" x="330" y="190" width="58" height="58" rx="8" fill={fills[5]} stroke="#0b3a6e" strokeWidth="6"/><rect onClick={()=>fill(6)} className="cursor-pointer" x="420" y="190" width="58" height="58" rx="8" fill={fills[6]} stroke="#0b3a6e" strokeWidth="6"/><circle onClick={()=>fill(7)} className="cursor-pointer" cx="535" cy="72" r="34" fill={fills[7]} stroke="#0b3a6e" strokeWidth="6"/><text x="300" y="350" textAnchor="middle" fontSize="24" fontWeight="800" fill="#0b3a6e">{t.title}</text></svg></div><div className="mt-3 flex justify-between text-xs font-bold text-blue-700"><span>{painted}/8 regions coloured</span><button onClick={()=>setFills(initialColours)} className="inline-flex items-center gap-1 rounded-full bg-sky-50 px-3 py-2"><RotateCcw className="h-3.5 w-3.5"/>Reset</button></div>{painted>=6&&<Finish onDone={onDone}/>}</RewardShell>}

function SpotGame({adventureId,onDone}:{adventureId:number;onDone:()=>void}){const targets=spotBoards[(adventureId-1)%spotBoards.length];const objects=useMemo(()=>[targets[0],decoys[0],targets[1],decoys[1],targets[2],decoys[2],targets[3],decoys[3],targets[4],decoys[4],decoys[5],decoys[6]],[targets]);const[found,setFound]=useState<string[]>([]);const tap=(obj:string)=>{if(targets.includes(obj)&&!found.includes(obj))setFound(v=>[...v,obj])};return <RewardShell title="Spot It!" subtitle="Find the five special objects. Tap each one when you spot it."><RewardPicture id={adventureId}/><div className="rounded-2xl bg-gradient-to-br from-sky-100 via-yellow-50 to-green-100 p-3"><div className="grid grid-cols-4 gap-2 sm:grid-cols-6">{objects.map((obj,i)=><button key={`${obj}-${i}`} onClick={()=>tap(obj)} className={`aspect-square rounded-xl border-2 bg-white/90 text-2xl shadow-sm sm:text-4xl ${found.includes(obj)?"border-green-400 bg-green-50":"border-white"}`}>{obj}{found.includes(obj)&&<span className="block text-[10px] text-green-700">✓</span>}</button>)}</div></div><p className="mt-3 text-center text-sm font-bold text-blue-800">Found {found.length} of 5</p>{found.length===5&&<Finish onDone={onDone}/>}</RewardShell>}

function MatchGame({adventureId,onDone}:{adventureId:number;onDone:()=>void}){const set=matchSets[adventureId]??matchSets[4];const[left,setLeft]=useState<number|null>(null);const[right,setRight]=useState<number|null>(null);const[done,setDone]=useState<number[]>([]);const[note,setNote]=useState("");const check=()=>{if(left===null||right===null)return;if(set.answer[left]===right){setDone(v=>[...v,left]);setNote("Great match! ✨")}else setNote("Almost - try a different pair.");setLeft(null);setRight(null)};return <RewardShell title="Tap to Match" subtitle="Tap one card on the left, then its matching card on the right. No dragging needed."><RewardPicture id={adventureId}/><div className="grid grid-cols-2 gap-2 sm:gap-3"><div className="grid gap-2">{set.left.map((x,i)=><button key={x} onClick={()=>!done.includes(i)&&(setLeft(i),setNote(""))} disabled={done.includes(i)} className={`min-h-14 rounded-xl border-2 p-2 text-left text-xs font-bold sm:p-3 sm:text-sm ${done.includes(i)?"border-green-300 bg-green-50":left===i?"border-purple-500 bg-purple-100":"border-sky-100"}`}>{done.includes(i)?"✓ ":""}{x}</button>)}</div><div className="grid gap-2">{set.right.map((x,i)=>{const li=set.answer.indexOf(i),matched=done.includes(li);return <button key={x} onClick={()=>!matched&&(setRight(i),setNote(""))} disabled={matched} className={`min-h-14 rounded-xl border-2 p-2 text-left text-xs font-bold sm:p-3 sm:text-sm ${matched?"border-green-300 bg-green-50":right===i?"border-orange-500 bg-orange-100":"border-sky-100"}`}>{matched?"✓ ":""}{x}</button>})}</div></div><div className="mt-4 flex items-center gap-3"><button onClick={check} disabled={left===null||right===null} className="rounded-full bg-blue-600 px-5 py-2.5 text-sm font-bold text-white disabled:opacity-40">Match Pair</button><span className="text-sm font-bold text-blue-700">{done.length}/4 matched</span></div>{note&&<p className="mt-3 rounded-xl bg-yellow-50 p-3 text-sm font-bold text-blue-900">🐱 Questy: {note}</p>}{done.length===4&&<Finish onDone={onDone}/>}</RewardShell>}

function PuzzleGame({adventureId,image,onDone}:{adventureId:number;image?:string;onDone:()=>void}){const initial=useMemo(()=>{const base=[0,1,2,3,4,5,6,7,8,9,10,11],shift=(adventureId*5)%12;return base.map((_,i)=>base[(i+shift)%12]).reverse()},[adventureId]);const[pieces,setPieces]=useState(initial);const[first,setFirst]=useState<number|null>(null);const solved=pieces.every((v,i)=>v===i);const tap=(position:number)=>{if(solved)return;if(first===null){setFirst(position);return}if(first===position){setFirst(null);return}setPieces(v=>{const n=[...v];[n[first],n[position]]=[n[position],n[first]];return n});setFirst(null)};const art=image||artData(adventureId);return <RewardShell title="12-Piece Puzzle" subtitle="Tap one piece, then another to swap them. Put all 12 pieces back in the right places."><div className="mb-3 overflow-hidden rounded-xl border-2 border-sky-100"><img src={art} alt="Puzzle picture preview" className="w-full"/></div><div className="mx-auto grid max-w-xl grid-cols-4 overflow-hidden rounded-2xl border-4 border-blue-900 bg-sky-100">{pieces.map((piece,pos)=>{const col=piece%4,row=Math.floor(piece/4);return <button key={pos} onClick={()=>tap(pos)} className={`relative aspect-[4/3] border border-white/70 ${first===pos?"ring-4 ring-inset ring-yellow-400":""}`} style={{backgroundImage:`url(${art})`,backgroundSize:"400% 300%",backgroundPosition:`${col*33.333}% ${row*50}%`}}><span className="absolute left-1 top-1 grid h-5 w-5 place-items-center rounded-full bg-white/90 text-[10px] font-black text-blue-900">{piece+1}</span></button>})}</div><div className="mt-3 flex items-center justify-between"><p className="text-xs font-bold text-blue-700">Tip: use the tiny numbers if you need help.</p><button onClick={()=>{setPieces(initial);setFirst(null)}} className="inline-flex items-center gap-1 rounded-full bg-sky-50 px-3 py-2 text-xs font-bold text-blue-800"><RotateCcw className="h-3.5 w-3.5"/>Shuffle</button></div>{solved&&<Finish onDone={onDone}/>}</RewardShell>}

export function RewardActivity({adventureId,image,onDone}:{adventureId:number;image?:string;onDone:()=>void}){const kind=rewardKinds[adventureId]??"spot";if(kind==="colour")return <ColourGame adventureId={adventureId} onDone={onDone}/>;if(kind==="match")return <MatchGame adventureId={adventureId} onDone={onDone}/>;if(kind==="puzzle")return <PuzzleGame adventureId={adventureId} image={image} onDone={onDone}/>;return <SpotGame adventureId={adventureId} onDone={onDone}/>;}
