"use client";

import { useMemo, useState } from "react";
import { RotateCcw, Sparkles } from "lucide-react";

type RewardKind = "colour" | "spot" | "match" | "puzzle";

const rewardKinds: Record<number, RewardKind> = {1:"colour",2:"spot",3:"puzzle",4:"match",5:"spot",6:"colour",7:"puzzle",8:"match",9:"spot",10:"puzzle",11:"colour",12:"match",13:"spot",14:"puzzle",15:"colour"};
const palette = ["#ef4444","#111827","#22c55e","#facc15","#7dd3fc","#a855f7","#f472b6","#92400e","#9ca3af"];
const initialColours = ["#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff"];
const spotBoards = [["🎨","📖","🤖","🏷️","⭐"],["✏️","📷","🎵","📚","🎬"],["💡","⚙️","🔧","📐","🧪"],["🎒","👟","🪑","💡","⌚"]];
const decoys = ["☁️","🍎","⚽","🌳","🥪","🚌","🌈"];
const matchSets: Record<number, {left:string[];right:string[];answer:number[]}>= {
  4:{left:["🌟 Starzo","🌿 Leafli","🚀 Zoomio","🐾 Pawza"],right:["⭐ Star logo","🍃 Leaf logo","🚀 Rocket logo","🐾 Paw logo"],answer:[0,1,2,3]},
  8:{left:["🎨 Drawing","📖 Story","📷 Photo","🎵 Song"],right:["👧 Artist","🧒 Writer","👦 Photographer","👧 Musician"],answer:[0,1,2,3]},
  12:{left:["💡 Lamp","🎒 Backpack","🪑 Chair","⌚ Watch"],right:["〰️ Wavy shade","🔷 Diamond pocket","🌙 Crescent back","⭐ Star face"],answer:[0,1,2,3]},
};

function RewardShell({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){
  return <section className="mx-auto max-w-4xl rounded-2xl border-2 border-orange-100 bg-white p-4 shadow-lg sm:rounded-[2rem] sm:p-7 sm:shadow-xl"><div className="flex items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-orange-100 text-2xl">🎁</div><div><p className="text-[11px] font-display font-black uppercase tracking-wider text-orange-600 sm:text-xs">Reward Activity</p><h3 className="font-display text-xl font-black text-blue-950 sm:text-3xl">{title}</h3><p className="mt-1 text-sm text-blue-700 sm:text-base">{subtitle}</p></div></div><div className="mt-4 sm:mt-6">{children}</div></section>;
}

function Finish({onDone}:{onDone:()=>void}){return <div className="mt-5 rounded-2xl bg-green-50 p-4 text-center"><p className="font-display text-lg font-black text-green-800">✨ Reward complete!</p><p className="mt-1 text-sm text-green-800">Great playing. Your Case File is ready.</p><button onClick={onDone} className="mt-3 inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-gradient-to-r from-blue-600 to-sky-500 px-6 py-2.5 text-sm font-display font-bold text-white shadow-md">Open My Case File <Sparkles className="h-4 w-4"/></button></div>}

function ColourGame({onDone}:{onDone:()=>void}){
  const [selected,setSelected]=useState(palette[0]); const [fills,setFills]=useState(initialColours); const painted=fills.filter(x=>x!=="#ffffff").length;
  const fill=(i:number)=>setFills(v=>v.map((c,n)=>n===i?selected:c));
  return <RewardShell title="Colour Quest" subtitle="Choose a colour, then tap the picture regions. There is no wrong colour."><div className="flex flex-wrap justify-center gap-2">{palette.map(c=><button key={c} aria-label={`Choose ${c}`} onClick={()=>setSelected(c)} className={`h-9 w-9 rounded-full border-4 shadow-sm transition sm:h-11 sm:w-11 ${selected===c?"scale-110 border-blue-500":"border-white"}`} style={{backgroundColor:c}}/>)}</div><div className="mx-auto mt-4 max-w-xl rounded-2xl bg-sky-50 p-2 sm:p-4"><svg viewBox="0 0 600 390" className="w-full" role="img" aria-label="Colourable Idea City picture"><rect x="5" y="5" width="590" height="380" rx="28" fill="#e0f2fe" stroke="#0b3a6e" strokeWidth="5"/><path d="M20 300 Q120 235 220 300 T420 300 T580 300 L580 370 L20 370Z" fill="#dcfce7" stroke="#0b3a6e" strokeWidth="5"/><path onClick={()=>fill(0)} className="cursor-pointer" d="M70 155 L160 80 L250 155 V305 H70Z" fill={fills[0]} stroke="#0b3a6e" strokeWidth="6"/><path onClick={()=>fill(1)} className="cursor-pointer" d="M60 155 L160 65 L260 155Z" fill={fills[1]} stroke="#0b3a6e" strokeWidth="6"/><rect onClick={()=>fill(2)} className="cursor-pointer" x="285" y="145" width="235" height="160" rx="12" fill={fills[2]} stroke="#0b3a6e" strokeWidth="6"/><path onClick={()=>fill(3)} className="cursor-pointer" d="M270 145 L402 65 L535 145Z" fill={fills[3]} stroke="#0b3a6e" strokeWidth="6"/><rect onClick={()=>fill(4)} className="cursor-pointer" x="105" y="210" width="70" height="95" rx="8" fill={fills[4]} stroke="#0b3a6e" strokeWidth="6"/><rect onClick={()=>fill(5)} className="cursor-pointer" x="330" y="190" width="58" height="58" rx="8" fill={fills[5]} stroke="#0b3a6e" strokeWidth="6"/><rect onClick={()=>fill(6)} className="cursor-pointer" x="420" y="190" width="58" height="58" rx="8" fill={fills[6]} stroke="#0b3a6e" strokeWidth="6"/><circle onClick={()=>fill(7)} className="cursor-pointer" cx="535" cy="72" r="34" fill={fills[7]} stroke="#0b3a6e" strokeWidth="6"/><text x="300" y="350" textAnchor="middle" fontSize="30" fontWeight="800" fill="#0b3a6e">IDEA CITY</text></svg></div><div className="mt-3 flex items-center justify-between text-xs font-bold text-blue-700"><span>{painted}/8 regions coloured</span><button onClick={()=>setFills(initialColours)} className="inline-flex items-center gap-1 rounded-full bg-sky-50 px-3 py-2"><RotateCcw className="h-3.5 w-3.5"/>Reset</button></div>{painted>=6&&<Finish onDone={onDone}/>}</RewardShell>
}

function SpotGame({adventureId,onDone}:{adventureId:number;onDone:()=>void}){
  const targets=spotBoards[(adventureId-1)%spotBoards.length]; const objects=useMemo(()=>[targets[0],decoys[0],targets[1],decoys[1],targets[2],decoys[2],targets[3],decoys[3],targets[4],decoys[4],decoys[5],decoys[6]],[targets]); const [found,setFound]=useState<string[]>([]);
  const tap=(obj:string)=>{if(targets.includes(obj)&&!found.includes(obj))setFound(v=>[...v,obj])};
  return <RewardShell title="Spot It!" subtitle="Find the five special objects. Tap each one when you spot it."><div className="rounded-2xl bg-gradient-to-br from-sky-100 via-yellow-50 to-green-100 p-4 sm:p-6"><div className="grid grid-cols-4 gap-3 sm:grid-cols-6 sm:gap-5">{objects.map((obj,i)=><button key={`${obj}-${i}`} onClick={()=>tap(obj)} className={`aspect-square rounded-2xl border-2 bg-white/90 text-3xl shadow-sm transition sm:text-4xl ${found.includes(obj)?"scale-95 border-green-400 bg-green-50":"border-white hover:scale-105"}`}>{obj}{found.includes(obj)&&<span className="block text-xs text-green-700">✓</span>}</button>)}</div></div><p className="mt-3 text-center text-sm font-bold text-blue-800">Found {found.length} of 5</p>{found.length===5&&<Finish onDone={onDone}/>}</RewardShell>
}

function MatchGame({adventureId,onDone}:{adventureId:number;onDone:()=>void}){
  const set=matchSets[adventureId]??matchSets[4]; const [left,setLeft]=useState<number|null>(null); const [right,setRight]=useState<number|null>(null); const [done,setDone]=useState<number[]>([]); const [note,setNote]=useState("");
  const check=()=>{if(left===null||right===null)return;if(set.answer[left]===right){setDone(v=>[...v,left]);setNote("Great match! ✨")}else setNote("Almost - try a different pair.");setLeft(null);setRight(null)};
  return <RewardShell title="Tap to Match" subtitle="Tap one card on the left, then its matching card on the right. No dragging needed."><div className="grid grid-cols-2 gap-3"><div className="grid gap-2">{set.left.map((x,i)=><button key={x} onClick={()=>{if(!done.includes(i)){setLeft(i);setNote("")}}} disabled={done.includes(i)} className={`min-h-14 rounded-xl border-2 p-3 text-left text-sm font-bold ${done.includes(i)?"border-green-300 bg-green-50 text-green-700":left===i?"border-purple-500 bg-purple-100":"border-sky-100 bg-white"}`}>{done.includes(i)?"✓ ":""}{x}</button>)}</div><div className="grid gap-2">{set.right.map((x,i)=>{const li=set.answer.indexOf(i);const matched=done.includes(li);return <button key={x} onClick={()=>{if(!matched){setRight(i);setNote("")}}} disabled={matched} className={`min-h-14 rounded-xl border-2 p-3 text-left text-sm font-bold ${matched?"border-green-300 bg-green-50 text-green-700":right===i?"border-orange-500 bg-orange-100":"border-sky-100 bg-white"}`}>{matched?"✓ ":""}{x}</button>})}</div></div><div className="mt-4 flex items-center gap-3"><button onClick={check} disabled={left===null||right===null} className="rounded-full bg-blue-600 px-5 py-2.5 text-sm font-bold text-white disabled:opacity-40">Match Pair</button><span className="text-sm font-bold text-blue-700">{done.length}/4 matched</span></div>{note&&<p className="mt-3 rounded-xl bg-yellow-50 p-3 text-sm font-bold text-blue-900">🐱 Questy: {note}</p>}{done.length===4&&<Finish onDone={onDone}/>}</RewardShell>
}

function PuzzleGame({adventureId,image,onDone}:{adventureId:number;image?:string;onDone:()=>void}){
  const initial=useMemo(()=>{const base=[0,1,2,3,4,5,6,7,8,9,10,11];const shift=(adventureId*5)%12;return base.map((_,i)=>base[(i+shift)%12]).reverse()},[adventureId]); const [pieces,setPieces]=useState(initial); const [first,setFirst]=useState<number|null>(null); const solved=pieces.every((v,i)=>v===i);
  const tap=(position:number)=>{if(solved)return;if(first===null){setFirst(position);return}if(first===position){setFirst(null);return}setPieces(v=>{const n=[...v];[n[first],n[position]]=[n[position],n[first]];return n});setFirst(null)}; const fallback="linear-gradient(135deg,#38bdf8 0%,#fef08a 35%,#fb923c 65%,#a78bfa 100%)";
  return <RewardShell title="12-Piece Puzzle" subtitle="Tap one piece, then another piece to swap them. Put all 12 pieces back in the right places."><div className="mx-auto grid max-w-xl grid-cols-4 overflow-hidden rounded-2xl border-4 border-blue-900 bg-sky-100">{pieces.map((piece,pos)=>{const col=piece%4,row=Math.floor(piece/4);return <button key={pos} onClick={()=>tap(pos)} className={`relative aspect-[4/3] border border-white/70 ${first===pos?"ring-4 ring-inset ring-yellow-400":""}`} style={{backgroundImage:image?`url(${image})`:fallback,backgroundSize:"400% 300%",backgroundPosition:`${col*33.333}% ${row*50}%`}}><span className="absolute left-1 top-1 grid h-5 w-5 place-items-center rounded-full bg-white/90 text-[10px] font-black text-blue-900">{piece+1}</span></button>})}</div><div className="mt-3 flex items-center justify-between gap-3"><p className="text-xs font-bold text-blue-700">Tip: use the tiny numbers if you need help.</p><button onClick={()=>{setPieces(initial);setFirst(null)}} className="inline-flex shrink-0 items-center gap-1 rounded-full bg-sky-50 px-3 py-2 text-xs font-bold text-blue-800"><RotateCcw className="h-3.5 w-3.5"/>Shuffle</button></div>{solved&&<Finish onDone={onDone}/>}</RewardShell>
}

export function RewardActivity({adventureId,image,onDone}:{adventureId:number;image?:string;onDone:()=>void}){const kind=rewardKinds[adventureId]??"spot";if(kind==="colour")return <ColourGame onDone={onDone}/>;if(kind==="match")return <MatchGame adventureId={adventureId} onDone={onDone}/>;if(kind==="puzzle")return <PuzzleGame adventureId={adventureId} image={image} onDone={onDone}/>;return <SpotGame adventureId={adventureId} onDone={onDone}/>;}
