"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { ArrowRight, Check, CheckCircle2, Sparkles, Target } from "lucide-react";
import { QuizQuestionCard } from "@/components/quiz";
import { toQuizQuestions, worldTheme, type World } from "@/lib/worlds";
import { WorldCompletionExperience } from "@/components/sections/WorldCompletionExperience";
import { DetectiveActivity } from "@/components/sections/DetectiveActivity";
import { CaseOneExperience } from "@/components/cases/CaseOneExperience";
import { CaseTwoExperience } from "@/components/cases/CaseTwoExperience";

function LessonHeading({ eyebrow, title }: { eyebrow: string; title: string }) { return <div className="text-center"><p className="font-display text-sm font-semibold uppercase tracking-[0.2em] text-detective-orange-500">{eyebrow}</p><h3 className="mt-2 font-display text-2xl font-bold text-detective-blue-900 sm:text-3xl">{title}</h3></div>; }
export function WorldDetailPanel({ world, isCompleted, onComplete, onNextWorld }: { world: World; isCompleted: boolean; onComplete: (correct: number, total: number) => void; onNextWorld: (worldId: number) => void; }) {
  const theme=worldTheme[world.color]; const questions=toQuizQuestions(world); const nextWorldId=world.id<15?world.id+1:null; const [answers,setAnswers]=useState<Record<string,boolean>>({});
  if(world.id===1)return <CaseOneExperience isCompleted={isCompleted} onComplete={onComplete}/>;
  if(world.id===2)return <CaseTwoExperience isCompleted={isCompleted} onComplete={onComplete}/>;
  const answeredCount=Object.keys(answers).length; const correctCount=Object.values(answers).filter(Boolean).length; const allAnswered=answeredCount===questions.length;
  return <motion.div initial={{opacity:0,height:0}} animate={{opacity:1,height:"auto"}} transition={{duration:.3}} className="overflow-hidden"><div className="mt-8 space-y-12 border-t-2 border-dashed border-detective-blue-200 pt-10">
    <section><LessonHeading eyebrow="The story" title={`Case ${world.id}: ${world.name}`}/><div className="mx-auto mt-8 max-w-3xl rounded-3xl border-2 border-detective-blue-100 bg-white p-6 shadow-lg sm:p-8"><p className="text-lg leading-relaxed text-detective-blue-900/85">{world.story}</p></div></section>
    <section><LessonHeading eyebrow="Your mission" title="What you will learn"/><div className="mx-auto mt-8 max-w-3xl rounded-3xl border-2 border-detective-blue-100 bg-white p-6 shadow-lg sm:p-8"><ul className="space-y-3">{world.objectives.map(o=><li key={o} className="flex items-start gap-3 text-lg"><span className="mt-1 grid h-6 w-6 shrink-0 place-items-center rounded-full bg-green-100"><Check className="h-4 w-4 text-green-700"/></span>{o}</li>)}</ul><p className="mt-6 rounded-2xl bg-detective-yellow-100 px-5 py-4 font-display font-semibold">🕵️ Briefing: {world.briefing}</p></div></section>
    <section><LessonHeading eyebrow="Mini lesson" title={world.miniLesson.heading}/><div className="mx-auto mt-8 max-w-3xl rounded-3xl border-2 border-detective-blue-100 bg-white p-6 shadow-lg sm:p-8"><p className="text-lg leading-relaxed">{world.miniLesson.body}</p><ul className="mt-6 grid gap-4 sm:grid-cols-3">{world.miniLesson.examples.map(e=><li key={e} className="rounded-3xl border-2 border-detective-blue-100 bg-detective-blue-50/60 p-5 text-center"><Sparkles className="mx-auto h-6 w-6 text-detective-orange-400"/><p className="mt-3 text-sm font-semibold">{e}</p></li>)}</ul></div></section>
    <DetectiveActivity world={world}/>
    <section><LessonHeading eyebrow="Detective steps 4–6" title="Detective questions"/><div className="mx-auto mt-8 max-w-3xl space-y-6">{questions.map((q,i)=><QuizQuestionCard key={q.id} question={q} counter={`Question ${i+1} of ${questions.length}`} allowRetry onAnswer={r=>setAnswers(c=>q.id in c?c:{...c,[q.id]:r.isCorrect})}/>)}</div></section>
    <section><LessonHeading eyebrow="Detective step 8 · Challenge" title={world.challenge.title}/><div className="mx-auto mt-8 max-w-3xl rounded-3xl border-2 border-detective-orange-400 bg-detective-orange-100/50 p-6 shadow-lg sm:p-8"><h4 className="flex items-center gap-2 font-display text-xl font-bold"><Target className="h-5 w-5 text-detective-orange-500"/>{world.activity.title}</h4><p className="mt-3 text-lg">{world.activity.instructions}</p><p className="mt-5 rounded-2xl bg-white px-5 py-4 text-lg"><span className="font-display font-bold">Extra credit: </span>{world.challenge.prompt}</p></div></section>
    <section><LessonHeading eyebrow="Mission complete" title="Case closed, detective!"/><div className={`mx-auto mt-8 max-w-3xl rounded-3xl border-2 bg-white p-6 text-center shadow-lg sm:p-8 ${theme.border}`}><span className="block text-6xl">{world.reward.badge}</span><h4 className="mt-4 font-display text-2xl font-bold">{world.reward.label}</h4><div className="mt-6 flex flex-wrap justify-center gap-3"><span className={`rounded-full px-5 py-2 font-display font-bold ${theme.chip}`}>⚡ +{world.xp} XP earned</span></div><div className="mt-8 flex flex-col items-center gap-3 sm:flex-row sm:justify-center">{isCompleted?<span className="inline-flex items-center gap-2 rounded-full bg-green-100 px-8 py-4 font-display text-lg font-semibold text-green-800"><CheckCircle2 className="h-5 w-5"/>World {world.id} complete</span>:<button onClick={()=>onComplete(correctCount,questions.length)} disabled={!allAnswered} className="inline-flex items-center gap-2 rounded-full bg-detective-orange-500 px-8 py-4 font-display text-lg font-semibold text-white disabled:opacity-50"><CheckCircle2 className="h-5 w-5"/>{allAnswered?"Claim my badge":`Answer all ${questions.length} questions (${answeredCount}/${questions.length})`}</button>}{nextWorldId&&isCompleted&&<button onClick={()=>onNextWorld(nextWorldId)} className="inline-flex items-center gap-2 rounded-full border-2 border-detective-blue-200 bg-white px-8 py-4 font-display text-lg font-semibold">Next: World {nextWorldId}<ArrowRight className="h-5 w-5"/></button>}</div></div></section>
    {isCompleted&&<WorldCompletionExperience world={world} onNextWorld={onNextWorld}/>} 
  </div></motion.div>;
}
