"use client";

import { useRouter } from "next/navigation";
import { ArrowLeft, Award, BookOpen, Brain, CheckCircle2, School, Sparkles } from "lucide-react";
import { Container } from "@/components/ui/Container";
import { SiteHeader } from "@/components/layout/SiteHeader";
import { SiteFooter } from "@/components/layout/SiteFooter";

const features = [[BookOpen,"15 Learning Worlds","A structured journey through creativity, brands, inventions, designs and IP problem-solving."],[Sparkles,"Stories & Activities","Picture stories, mysteries, quizzes, problem-solving cases and creative reward activities."],[Brain,"Learn by Investigating","Children practise observation, reasoning and evidence-based thinking instead of only memorising definitions."],[Award,"Progress & Achievement","XP, badges and certificates help young detectives celebrate progress through the learning journey."]];
const path = [["Creator Park","Worlds 1–3","Creators, creations and copyright foundations."],["Brand Street","Worlds 4–7","Brands, names, logos and trademarks."],["Inventor Lab","Worlds 8–10","Inventions, problem-solving and patents."],["Creator Studio & Design District","Worlds 11–13","Creative works, appearance and designs."],["Detective HQ","Worlds 14–15","Applying what children have learned to IP mysteries and challenges."]];

export default function ParentsEducatorsPage() {
  const router = useRouter();
  return <><SiteHeader/><main className="bg-gradient-to-b from-sky-50 via-white to-yellow-50 py-8 sm:py-12"><Container>
    <button type="button" onClick={()=>router.back()} className="mb-6 inline-flex items-center gap-2 rounded-full border-2 border-detective-blue-100 bg-white px-4 py-2 font-display text-sm font-bold text-detective-blue-700 shadow-sm transition hover:border-detective-blue-300 hover:bg-detective-blue-50"><ArrowLeft className="h-4 w-4"/>Back</button>
    <section className="mx-auto max-w-4xl text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-3xl bg-detective-yellow-300 text-detective-blue-900"><School className="h-8 w-8"/></div><p className="mt-5 font-display font-bold uppercase tracking-[0.2em] text-detective-orange-600">For Parents & Educators</p><h1 className="mt-3 font-display text-4xl font-bold text-detective-blue-900 sm:text-5xl">Intellectual property education made simple for young learners</h1><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-detective-blue-800">IP2Kids uses stories, mysteries, quizzes and creative activities to introduce children to ideas, creativity, copyright, trademarks, inventions and designs in an approachable way.</p><div className="mx-auto mt-6 inline-flex items-center gap-2 rounded-full bg-green-50 px-5 py-3 font-display font-bold text-green-800"><CheckCircle2 className="h-5 w-5"/>All 15 learning worlds are free.</div></section>
    <section className="mx-auto mt-12 grid max-w-5xl gap-5 sm:grid-cols-2">{features.map(([Icon,title,text])=><article key={String(title)} className="rounded-3xl border-2 border-detective-blue-100 bg-white p-6 shadow-sm"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-sky-100 text-detective-blue-700"><Icon className="h-6 w-6"/></span><h2 className="mt-4 font-display text-xl font-bold text-detective-blue-900">{String(title)}</h2><p className="mt-2 leading-7 text-detective-blue-700">{String(text)}</p></article>)}</section>
    <section className="mx-auto mt-14 max-w-5xl rounded-[2rem] bg-white p-6 shadow-sm sm:p-9"><p className="font-display font-bold uppercase tracking-widest text-detective-orange-600">Learning Path</p><h2 className="mt-2 font-display text-3xl font-bold text-detective-blue-900">The Little IP Detectives journey</h2><div className="mt-7 grid gap-4">{path.map(([place,worlds,lesson],i)=><div key={place} className="flex gap-4 rounded-2xl bg-sky-50 p-5"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-detective-yellow-300 font-display font-bold text-detective-blue-900">{i+1}</span><div><div className="flex flex-wrap items-baseline gap-x-3"><h3 className="font-display text-lg font-bold text-detective-blue-900">{place}</h3><span className="font-display text-sm font-bold text-detective-orange-600">{worlds}</span></div><p className="mt-1 text-detective-blue-700">{lesson}</p></div></div>)}</div></section>
  </Container></main><SiteFooter/></>;
}
