"use client";

import { useRouter } from "next/navigation";
import { ArrowLeft, BookOpen, Brain, CheckCircle2, Headphones, School, Sparkles } from "lucide-react";
import { Container } from "@/components/ui/Container";
import { SiteHeader } from "@/components/layout/SiteHeader";
import { SiteFooter } from "@/components/layout/SiteFooter";

const features = [
  [BookOpen,"15 Idea Adventures","A progressive first introduction to creators, copyright, brands, trademarks, inventions, patents and product designs."],
  [Headphones,"Read or Listen","Every adventure begins with one child-friendly passage. Children can read independently or use Read to me to hear the passage in a gentle voice."],
  [Brain,"Understand Before Terminology","Children experience the situation first, answer five easy clue questions based mainly on the passage, and then meet the relevant IP word through Questy's Discovery."],
  [Sparkles,"Encouraging, Not Exam-Like","Retry feedback stays positive. Legal definitions are not memorised, and the final 10-question review is for reinforcement and celebration rather than pass or fail."],
];
const path = [["Creator Park","Adventures 1–3","Creators, creations, giving credit and an introduction to copyright."],["Brand Street","Adventures 4–7","Brands, trademarks, similar signs, brand clues, names and slogans."],["Inventor Lab","Adventures 8–10","Problems, inventions, patents and looking at what makes an invention different."],["Design District","Adventures 11–13","Product appearance, original design choices and how different IP ideas can exist in one product."],["Detective HQ","Adventures 14–15","Choosing the right starting IP clue and bringing the whole journey together."]];

export default function ParentsEducatorsPage() {
  const router = useRouter();
  return <><SiteHeader/><main className="bg-gradient-to-b from-sky-50 via-white to-yellow-50 py-8 sm:py-12"><Container>
    <button type="button" onClick={()=>router.back()} className="mb-6 inline-flex items-center gap-1.5 rounded-full border-2 border-detective-blue-100 bg-white px-3 py-1.5 font-display text-xs font-bold text-detective-blue-700 shadow-sm transition hover:border-detective-blue-300 hover:bg-detective-blue-50"><ArrowLeft className="h-3.5 w-3.5"/>Back</button>
    <section className="mx-auto max-w-4xl text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-3xl bg-detective-yellow-300 text-detective-blue-900"><School className="h-8 w-8"/></div><p className="mt-5 font-display font-bold uppercase tracking-[0.2em] text-detective-orange-600">For Parents & Educators</p><h1 className="mt-3 font-display text-4xl font-bold text-detective-blue-900 sm:text-5xl">A gentle first introduction to intellectual property</h1><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-detective-blue-800">IP2Kids is designed for children beginning with zero knowledge of intellectual property. The website introduces IP through familiar situations and simple language, while deeper legal learning belongs in books, classroom materials and later resources.</p><div className="mx-auto mt-6 inline-flex items-center gap-2 rounded-full bg-green-50 px-5 py-3 font-display font-bold text-green-800"><CheckCircle2 className="h-5 w-5"/>All 15 Idea Adventures are free.</div></section>
    <section className="mx-auto mt-12 grid max-w-5xl gap-5 sm:grid-cols-2">{features.map(([Icon,title,text])=><article key={String(title)} className="rounded-3xl border-2 border-detective-blue-100 bg-white p-6 shadow-sm"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-sky-100 text-detective-blue-700"><Icon className="h-6 w-6"/></span><h2 className="mt-4 font-display text-xl font-bold text-detective-blue-900">{String(title)}</h2><p className="mt-2 leading-7 text-detective-blue-700">{String(text)}</p></article>)}</section>
    <section className="mx-auto mt-14 max-w-5xl rounded-[2rem] bg-white p-6 shadow-sm sm:p-9"><p className="font-display font-bold uppercase tracking-widest text-detective-orange-600">How an Adventure Works</p><h2 className="mt-2 font-display text-3xl font-bold text-detective-blue-900">Story first. Discover the idea. Keep exploring.</h2><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-sky-50 p-5"><p className="font-display font-bold text-detective-blue-900">1. Adventure Passage</p><p className="mt-1 text-sm leading-6 text-detective-blue-700">One short passage presents the situation. A Read to me option supports children who prefer listening.</p></div><div className="rounded-2xl bg-sky-50 p-5"><p className="font-display font-bold text-detective-blue-900">2. Find the Clues</p><p className="mt-1 text-sm leading-6 text-detective-blue-700">Five easy questions are based mainly on the passage the child has just read or heard.</p></div><div className="rounded-2xl bg-yellow-50 p-5"><p className="font-display font-bold text-detective-blue-900">3. Questy&apos;s Discovery</p><p className="mt-1 text-sm leading-6 text-detective-blue-700">The IP word is introduced only after the child understands the situation, using simple child-friendly explanations.</p></div><div className="rounded-2xl bg-yellow-50 p-5"><p className="font-display font-bold text-detective-blue-900">4. Case File</p><p className="mt-1 text-sm leading-6 text-detective-blue-700">Three short “I discovered...” takeaways reinforce the main idea before the child continues to the next adventure.</p></div></div><p className="mt-5 rounded-2xl bg-green-50 p-4 text-sm leading-6 text-green-900"><strong>After Adventure 15:</strong> Questy&apos;s Ultimate IP Challenge provides 10 final mysteries. Children may retry, receive immediate feedback and complete the journey regardless of score.</p></section>
    <section className="mx-auto mt-14 max-w-5xl rounded-[2rem] bg-white p-6 shadow-sm sm:p-9"><p className="font-display font-bold uppercase tracking-widest text-detective-orange-600">Adventure Path</p><h2 className="mt-2 font-display text-3xl font-bold text-detective-blue-900">Questy&apos;s 15 Idea Adventures</h2><div className="mt-7 grid gap-4">{path.map(([place,adventures,lesson],i)=><div key={place} className="flex gap-4 rounded-2xl bg-sky-50 p-5"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-detective-yellow-300 font-display font-bold text-detective-blue-900">{i+1}</span><div><div className="flex flex-wrap items-baseline gap-x-3"><h3 className="font-display text-lg font-bold text-detective-blue-900">{place}</h3><span className="font-display text-sm font-bold text-detective-orange-600">{adventures}</span></div><p className="mt-1 text-detective-blue-700">{lesson}</p></div></div>)}</div></section>
  </Container></main><SiteFooter/></>;
}
