"use client";

import { useRouter } from "next/navigation";
import { ArrowLeft, Award, BookOpen, Brain, CheckCircle2, School, Sparkles } from "lucide-react";
import { Container } from "@/components/ui/Container";
import { SiteHeader } from "@/components/layout/SiteHeader";
import { SiteFooter } from "@/components/layout/SiteFooter";

const features = [[BookOpen,"15 Idea Adventures","A playful introduction to creativity, brands, inventions, stories, designs and intellectual property."],[Sparkles,"Stories & Activities","Short stories, questions, challenges and creative reward activities keep the experience light and engaging."],[Brain,"Spark Curiosity","The website introduces big ideas in simple language and encourages children to continue reading and learning."],[Award,"Progress & Celebration","XP, stars, badges and certificates celebrate children as they move through Questy's adventures."]];
const path = [["Creator Park","Adventures 1–3","Ideas, creators, creative works and respectful creativity."],["Brand Street","Adventures 4–7","Brand names, logos, packaging and memorable brand clues."],["Inventor Lab","Adventures 8–10","Problems, inventions and an introduction to patents."],["Creator Studio & Design District","Adventures 11–13","Stories, creative works, appearance and designs."],["Adventure HQ","Adventures 14–15","Bringing the big ideas together in playful final challenges."]];

export default function ParentsEducatorsPage() {
  const router = useRouter();
  return <><SiteHeader/><main className="bg-gradient-to-b from-sky-50 via-white to-yellow-50 py-8 sm:py-12"><Container>
    <button type="button" onClick={()=>router.back()} className="mb-6 inline-flex items-center gap-2 rounded-full border-2 border-detective-blue-100 bg-white px-4 py-2 font-display text-sm font-bold text-detective-blue-700 shadow-sm transition hover:border-detective-blue-300 hover:bg-detective-blue-50"><ArrowLeft className="h-4 w-4"/>Back</button>
    <section className="mx-auto max-w-4xl text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-3xl bg-detective-yellow-300 text-detective-blue-900"><School className="h-8 w-8"/></div><p className="mt-5 font-display font-bold uppercase tracking-[0.2em] text-detective-orange-600">For Parents & Educators</p><h1 className="mt-3 font-display text-4xl font-bold text-detective-blue-900 sm:text-5xl">A playful first introduction to intellectual property</h1><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-detective-blue-800">IP2Kids uses Questy's Idea Adventures to make children curious about creativity, brands, inventions, copyright and designs — and encourage them to keep reading and discovering beyond the website.</p><div className="mx-auto mt-6 inline-flex items-center gap-2 rounded-full bg-green-50 px-5 py-3 font-display font-bold text-green-800"><CheckCircle2 className="h-5 w-5"/>All 15 Idea Adventures are free.</div></section>
    <section className="mx-auto mt-12 grid max-w-5xl gap-5 sm:grid-cols-2">{features.map(([Icon,title,text])=><article key={String(title)} className="rounded-3xl border-2 border-detective-blue-100 bg-white p-6 shadow-sm"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-sky-100 text-detective-blue-700"><Icon className="h-6 w-6"/></span><h2 className="mt-4 font-display text-xl font-bold text-detective-blue-900">{String(title)}</h2><p className="mt-2 leading-7 text-detective-blue-700">{String(text)}</p></article>)}</section>
    <section className="mx-auto mt-14 max-w-5xl rounded-[2rem] bg-white p-6 shadow-sm sm:p-9"><p className="font-display font-bold uppercase tracking-widest text-detective-orange-600">Adventure Path</p><h2 className="mt-2 font-display text-3xl font-bold text-detective-blue-900">Questy&apos;s Idea Adventures</h2><div className="mt-7 grid gap-4">{path.map(([place,adventures,lesson],i)=><div key={place} className="flex gap-4 rounded-2xl bg-sky-50 p-5"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-detective-yellow-300 font-display font-bold text-detective-blue-900">{i+1}</span><div><div className="flex flex-wrap items-baseline gap-x-3"><h3 className="font-display text-lg font-bold text-detective-blue-900">{place}</h3><span className="font-display text-sm font-bold text-detective-orange-600">{adventures}</span></div><p className="mt-1 text-detective-blue-700">{lesson}</p></div></div>)}</div></section>
  </Container></main><SiteFooter/></>;
}
